#! /usr/bin/env bash
exec /home/juan-diego/miniconda3/envs/digital/bin/vvp -f "$0" "$@" <<'# EOF'
:ivl_version "13.0 (devel)" "(0_8-6859-gf50cc35d2-dirty)";
:ivl_delay_selection "TYPICAL";
:vpi_time_precision - 12;
:vpi_module "/home/juan-diego/miniconda3/envs/digital/lib/ivl/system.vpi";
:vpi_module "/home/juan-diego/miniconda3/envs/digital/lib/ivl/vhdl_sys.vpi";
:vpi_module "/home/juan-diego/miniconda3/envs/digital/lib/ivl/vhdl_textio.vpi";
:vpi_module "/home/juan-diego/miniconda3/envs/digital/lib/ivl/v2005_math.vpi";
:vpi_module "/home/juan-diego/miniconda3/envs/digital/lib/ivl/va_math.vpi";
S_0x2e7f070 .scope module, "tb_led_panel_video" "tb_led_panel_video" 2 3;
 .timescale -9 -12;
v0x2ecc150_0 .net "LATCH", 0 0, L_0x2e8dea0;  1 drivers
v0x2ecc210_0 .net "LP_CLK", 0 0, L_0x2e8a7e0;  1 drivers
v0x2ecc2b0_0 .net "NOE", 0 0, L_0x2e83650;  1 drivers
v0x2ecc350_0 .net "RGB0", 2 0, L_0x2ede9f0;  1 drivers
v0x2ecc3f0_0 .net "RGB1", 2 0, L_0x2edeb30;  1 drivers
v0x2ecc490_0 .net "ROW", 4 0, v0x2ec4b50_0;  1 drivers
v0x2ecc580_0 .var "clk", 0 0;
v0x2ecc620_0 .var "init", 0 0;
v0x2ecc6c0_0 .var "rst", 0 0;
S_0x2e950f0 .scope module, "DUT" "led_panel_video" 2 41, 3 1 0, S_0x2e7f070;
 .timescale -9 -12;
    .port_info 0 /INPUT 1 "rst";
    .port_info 1 /INPUT 1 "clk";
    .port_info 2 /INPUT 1 "init";
    .port_info 3 /OUTPUT 1 "LP_CLK";
    .port_info 4 /OUTPUT 1 "LATCH";
    .port_info 5 /OUTPUT 1 "NOE";
    .port_info 6 /OUTPUT 5 "ROW";
    .port_info 7 /OUTPUT 3 "RGB0";
    .port_info 8 /OUTPUT 3 "RGB1";
P_0x2df8870 .param/l "DELAY" 1 3 61, +C4<00000000000000000000000000001010>;
P_0x2df88b0 .param/l "N_FRAMES" 0 3 2, +C4<00000000000000000000000000011000>;
P_0x2df88f0 .param/l "TOTAL_PIXELS" 1 3 16, +C4<0000000000000000000000000000000000000000000000001100000000000000>;
L_0x2e8dea0 .functor NOT 1, v0x2ec6680_0, C4<0>, C4<0>, C4<0>;
L_0x2e83650 .functor BUFZ 1, v0x2ec67c0_0, C4<0>, C4<0>, C4<0>;
L_0x2e8a7e0 .functor AND 1, v0x2eca560_0, v0x2ec6860_0, C4<1>, C4<1>;
v0x2ec9470_0 .net "COL", 5 0, v0x2ec1ee0_0;  1 drivers
v0x2ec9550_0 .net "FRAME", 4 0, L_0x2ede8b0;  1 drivers
v0x2ec9610_0 .net "LATCH", 0 0, L_0x2e8dea0;  alias, 1 drivers
v0x2ec96e0_0 .net "LP_CLK", 0 0, L_0x2e8a7e0;  alias, 1 drivers
v0x2ec97a0_0 .net "NOE", 0 0, L_0x2e83650;  alias, 1 drivers
v0x2ec98b0_0 .net "PIX_ADDR", 11 0, L_0x2ecc940;  1 drivers
v0x2ec9970_0 .net "PX_CLK_EN", 0 0, v0x2ec6860_0;  1 drivers
v0x2ec9a40_0 .net "RGB0", 2 0, L_0x2ede9f0;  alias, 1 drivers
v0x2ec9ae0_0 .net "RGB1", 2 0, L_0x2edeb30;  alias, 1 drivers
v0x2ec9bc0_0 .net "ROW", 4 0, v0x2ec4b50_0;  alias, 1 drivers
v0x2ec9cb0_0 .net *"_ivl_10", 15 0, L_0x2eccad0;  1 drivers
L_0x750b0771f060 .functor BUFT 1, C4<00000000000>, C4<0>, C4<0>, C4<0>;
v0x2ec9d70_0 .net *"_ivl_13", 10 0, L_0x750b0771f060;  1 drivers
L_0x750b0771f0a8 .functor BUFT 1, C4<0000100000000000>, C4<0>, C4<0>, C4<0>;
v0x2ec9e50_0 .net/2u *"_ivl_14", 15 0, L_0x750b0771f0a8;  1 drivers
v0x2ec9f30_0 .net *"_ivl_17", 15 0, L_0x2edcbd0;  1 drivers
v0x2eca010_0 .net *"_ivl_18", 15 0, L_0x2edcd10;  1 drivers
L_0x750b0771f0f0 .functor BUFT 1, C4<0000>, C4<0>, C4<0>, C4<0>;
v0x2eca0f0_0 .net *"_ivl_21", 3 0, L_0x750b0771f0f0;  1 drivers
v0x2eca1d0_0 .net *"_ivl_4", 10 0, L_0x2ecc850;  1 drivers
L_0x750b0771f018 .functor BUFT 1, C4<0>, C4<0>, C4<0>, C4<0>;
v0x2eca3c0_0 .net *"_ivl_9", 0 0, L_0x750b0771f018;  1 drivers
v0x2eca4a0_0 .net "clk", 0 0, v0x2ecc580_0;  1 drivers
v0x2eca560_0 .var "clk1", 0 0;
v0x2eca600_0 .var "clk_counter", 4 0;
v0x2eca6e0_0 .net "count_delay", 10 0, v0x2ec2de0_0;  1 drivers
v0x2eca7a0_0 .net "delay", 10 0, v0x2ec7d80_0;  1 drivers
v0x2eca8b0_0 .net "index", 1 0, v0x2ec3c40_0;  1 drivers
v0x2eca9c0_0 .net "init", 0 0, v0x2ecc620_0;  1 drivers
v0x2ecaa80_0 .net "mem_data", 23 0, v0x2ec87c0_0;  1 drivers
v0x2ecab90_0 .net "rst", 0 0, v0x2ecc6c0_0;  1 drivers
v0x2ecac50_0 .net "tmp_latch", 0 0, v0x2ec6680_0;  1 drivers
v0x2ecacf0_0 .net "tmp_noe", 0 0, v0x2ec67c0_0;  1 drivers
v0x2ecad90_0 .net "w_CHANGE", 0 0, v0x2ec6120_0;  1 drivers
v0x2ecae80_0 .net "w_INC_C", 0 0, v0x2ec6200_0;  1 drivers
v0x2ecaf70_0 .net "w_INC_D", 0 0, v0x2ec62f0_0;  1 drivers
v0x2ecb060_0 .net "w_INC_F", 0 0, v0x2ec63f0_0;  1 drivers
v0x2ecb150_0 .net "w_INC_I", 0 0, v0x2ec64c0_0;  1 drivers
v0x2ecb240_0 .net "w_INC_R", 0 0, v0x2ec65b0_0;  1 drivers
v0x2ecb330_0 .net "w_LD", 0 0, v0x2ec6720_0;  1 drivers
v0x2ecb420_0 .net "w_RST_C", 0 0, v0x2ec6900_0;  1 drivers
v0x2ecb510_0 .net "w_RST_D", 0 0, v0x2ec69d0_0;  1 drivers
v0x2ecb600_0 .net "w_RST_F", 0 0, v0x2ec6aa0_0;  1 drivers
v0x2ecb6f0_0 .net "w_RST_I", 0 0, v0x2ec6b70_0;  1 drivers
v0x2ecb7e0_0 .net "w_RST_R", 0 0, v0x2ec6c40_0;  1 drivers
v0x2ecb8d0_0 .net "w_SHD", 0 0, v0x2ec6d10_0;  1 drivers
v0x2ecb9c0_0 .net "w_ZC", 0 0, L_0x2edd9b0;  1 drivers
v0x2ecbab0_0 .net "w_ZD", 0 0, v0x2e8dfb0_0;  1 drivers
v0x2ecbba0_0 .net "w_ZFRAME", 0 0, L_0x2ede7c0;  1 drivers
v0x2ecbc90_0 .net "w_ZI", 0 0, L_0x2ede310;  1 drivers
v0x2ecbd80_0 .net "w_ZR", 0 0, L_0x2edd4c0;  1 drivers
v0x2ecbe70_0 .net "w_address_image", 15 0, L_0x2edce00;  1 drivers
v0x2ecbf10_0 .net "w_data", 23 0, v0x2ec9230_0;  1 drivers
E_0x2e44430 .event posedge, v0x2eca4a0_0;
L_0x2ecc850 .concat [ 6 5 0 0], v0x2ec1ee0_0, v0x2ec4b50_0;
L_0x2ecc940 .concat [ 11 1 0 0], L_0x2ecc850, L_0x750b0771f018;
L_0x2eccad0 .concat [ 5 11 0 0], L_0x2ede8b0, L_0x750b0771f060;
L_0x2edcbd0 .arith/mult 16, L_0x2eccad0, L_0x750b0771f0a8;
L_0x2edcd10 .concat [ 12 4 0 0], L_0x2ecc940, L_0x750b0771f0f0;
L_0x2edce00 .arith/sum 16, L_0x2edcbd0, L_0x2edcd10;
L_0x2ede8b0 .part v0x2ec1100_0, 0, 5;
L_0x2ede9f0 .part v0x2ec5140_0, 3, 3;
L_0x2edeb30 .part v0x2ec5140_0, 0, 3;
L_0x2edec70 .reduce/nor v0x2ecc6c0_0;
S_0x2e81070 .scope module, "Comparador0" "Comparador" 3 127, 4 1 0, S_0x2e950f0;
 .timescale -9 -12;
    .port_info 0 /INPUT 11 "in1";
    .port_info 1 /INPUT 11 "in2";
    .port_info 2 /OUTPUT 1 "out";
P_0x2e30990 .param/l "width" 0 4 2, +C4<00000000000000000000000000001010>;
v0x2e93e50_0 .net "in1", 10 0, v0x2ec7d80_0;  alias, 1 drivers
v0x2e94b70_0 .net "in2", 10 0, v0x2ec2de0_0;  alias, 1 drivers
v0x2e8dfb0_0 .var "out", 0 0;
E_0x2e44900 .event anyedge, v0x2e93e50_0, v0x2e94b70_0;
S_0x2ec0860 .scope module, "Contador_Frame" "Contador" 3 112, 5 1 0, S_0x2e950f0;
 .timescale -9 -12;
    .port_info 0 /INPUT 1 "clk";
    .port_info 1 /INPUT 1 "reset";
    .port_info 2 /INPUT 1 "inc";
    .port_info 3 /OUTPUT 6 "outc";
    .port_info 4 /OUTPUT 1 "zero";
P_0x2ec0a40 .param/l "width" 0 5 2, +C4<00000000000000000000000000000101>;
v0x2e837a0_0 .net *"_ivl_0", 31 0, L_0x2ede400;  1 drivers
L_0x750b0771f690 .functor BUFT 1, C4<00>, C4<0>, C4<0>, C4<0>;
v0x2e8a930_0 .net/2s *"_ivl_10", 1 0, L_0x750b0771f690;  1 drivers
v0x2e88330_0 .net *"_ivl_12", 1 0, L_0x2ede630;  1 drivers
L_0x750b0771f5b8 .functor BUFT 1, C4<00000000000000000000000000>, C4<0>, C4<0>, C4<0>;
v0x2e85d60_0 .net *"_ivl_3", 25 0, L_0x750b0771f5b8;  1 drivers
L_0x750b0771f600 .functor BUFT 1, C4<00000000000000000000000000000000>, C4<0>, C4<0>, C4<0>;
v0x2ec0cb0_0 .net/2u *"_ivl_4", 31 0, L_0x750b0771f600;  1 drivers
v0x2ec0de0_0 .net *"_ivl_6", 0 0, L_0x2ede4f0;  1 drivers
L_0x750b0771f648 .functor BUFT 1, C4<01>, C4<0>, C4<0>, C4<0>;
v0x2ec0ea0_0 .net/2s *"_ivl_8", 1 0, L_0x750b0771f648;  1 drivers
v0x2ec0f80_0 .net "clk", 0 0, v0x2eca560_0;  1 drivers
v0x2ec1040_0 .net "inc", 0 0, v0x2ec63f0_0;  alias, 1 drivers
v0x2ec1100_0 .var "outc", 5 0;
v0x2ec11e0_0 .net "reset", 0 0, v0x2ec6aa0_0;  alias, 1 drivers
v0x2ec12a0_0 .net "zero", 0 0, L_0x2ede7c0;  alias, 1 drivers
E_0x2e44c20 .event negedge, v0x2ec0f80_0;
L_0x2ede400 .concat [ 6 26 0 0], v0x2ec1100_0, L_0x750b0771f5b8;
L_0x2ede4f0 .cmp/eq 32, L_0x2ede400, L_0x750b0771f600;
L_0x2ede630 .functor MUXZ 2, L_0x750b0771f690, L_0x750b0771f648, L_0x2ede4f0, C4<>;
L_0x2ede7c0 .part L_0x2ede630, 0, 1;
S_0x2ec1400 .scope module, "Contador_col" "Contador" 3 89, 5 1 0, S_0x2e950f0;
 .timescale -9 -12;
    .port_info 0 /INPUT 1 "clk";
    .port_info 1 /INPUT 1 "reset";
    .port_info 2 /INPUT 1 "inc";
    .port_info 3 /OUTPUT 6 "outc";
    .port_info 4 /OUTPUT 1 "zero";
P_0x2ec1590 .param/l "width" 0 5 2, +C4<00000000000000000000000000000101>;
v0x2ec1740_0 .net *"_ivl_0", 31 0, L_0x2edd5b0;  1 drivers
L_0x750b0771f330 .functor BUFT 1, C4<00>, C4<0>, C4<0>, C4<0>;
v0x2ec1820_0 .net/2s *"_ivl_10", 1 0, L_0x750b0771f330;  1 drivers
v0x2ec1900_0 .net *"_ivl_12", 1 0, L_0x2edd820;  1 drivers
L_0x750b0771f258 .functor BUFT 1, C4<00000000000000000000000000>, C4<0>, C4<0>, C4<0>;
v0x2ec19f0_0 .net *"_ivl_3", 25 0, L_0x750b0771f258;  1 drivers
L_0x750b0771f2a0 .functor BUFT 1, C4<00000000000000000000000000000000>, C4<0>, C4<0>, C4<0>;
v0x2ec1ad0_0 .net/2u *"_ivl_4", 31 0, L_0x750b0771f2a0;  1 drivers
v0x2ec1c00_0 .net *"_ivl_6", 0 0, L_0x2edd730;  1 drivers
L_0x750b0771f2e8 .functor BUFT 1, C4<01>, C4<0>, C4<0>, C4<0>;
v0x2ec1cc0_0 .net/2s *"_ivl_8", 1 0, L_0x750b0771f2e8;  1 drivers
v0x2ec1da0_0 .net "clk", 0 0, v0x2eca560_0;  alias, 1 drivers
v0x2ec1e40_0 .net "inc", 0 0, v0x2ec6200_0;  alias, 1 drivers
v0x2ec1ee0_0 .var "outc", 5 0;
v0x2ec1fc0_0 .net "reset", 0 0, v0x2ec6900_0;  alias, 1 drivers
v0x2ec2080_0 .net "zero", 0 0, L_0x2edd9b0;  alias, 1 drivers
L_0x2edd5b0 .concat [ 6 26 0 0], v0x2ec1ee0_0, L_0x750b0771f258;
L_0x2edd730 .cmp/eq 32, L_0x2edd5b0, L_0x750b0771f2a0;
L_0x2edd820 .functor MUXZ 2, L_0x750b0771f330, L_0x750b0771f2e8, L_0x2edd730, C4<>;
L_0x2edd9b0 .part L_0x2edd820, 0, 1;
S_0x2ec2210 .scope module, "Contador_delay" "Contador" 3 97, 5 1 0, S_0x2e950f0;
 .timescale -9 -12;
    .port_info 0 /INPUT 1 "clk";
    .port_info 1 /INPUT 1 "reset";
    .port_info 2 /INPUT 1 "inc";
    .port_info 3 /OUTPUT 11 "outc";
    .port_info 4 /OUTPUT 1 "zero";
P_0x2ec23a0 .param/l "width" 0 5 2, +C4<00000000000000000000000000001010>;
v0x2ec25b0_0 .net *"_ivl_0", 31 0, L_0x2eddaa0;  1 drivers
L_0x750b0771f450 .functor BUFT 1, C4<00>, C4<0>, C4<0>, C4<0>;
v0x2ec26b0_0 .net/2s *"_ivl_10", 1 0, L_0x750b0771f450;  1 drivers
v0x2ec2790_0 .net *"_ivl_12", 1 0, L_0x2eddcd0;  1 drivers
L_0x750b0771f378 .functor BUFT 1, C4<000000000000000000000>, C4<0>, C4<0>, C4<0>;
v0x2ec2880_0 .net *"_ivl_3", 20 0, L_0x750b0771f378;  1 drivers
L_0x750b0771f3c0 .functor BUFT 1, C4<00000000000000000000000000000000>, C4<0>, C4<0>, C4<0>;
v0x2ec2960_0 .net/2u *"_ivl_4", 31 0, L_0x750b0771f3c0;  1 drivers
v0x2ec2a90_0 .net *"_ivl_6", 0 0, L_0x2eddb90;  1 drivers
L_0x750b0771f408 .functor BUFT 1, C4<01>, C4<0>, C4<0>, C4<0>;
v0x2ec2b50_0 .net/2s *"_ivl_8", 1 0, L_0x750b0771f408;  1 drivers
v0x2ec2c30_0 .net "clk", 0 0, v0x2eca560_0;  alias, 1 drivers
v0x2ec2d20_0 .net "inc", 0 0, v0x2ec62f0_0;  alias, 1 drivers
v0x2ec2de0_0 .var "outc", 10 0;
v0x2ec2ea0_0 .net "reset", 0 0, v0x2ec69d0_0;  alias, 1 drivers
v0x2ec2f40_0 .net "zero", 0 0, L_0x2edde60;  1 drivers
L_0x2eddaa0 .concat [ 11 21 0 0], v0x2ec2de0_0, L_0x750b0771f378;
L_0x2eddb90 .cmp/eq 32, L_0x2eddaa0, L_0x750b0771f3c0;
L_0x2eddcd0 .functor MUXZ 2, L_0x750b0771f450, L_0x750b0771f408, L_0x2eddb90, C4<>;
L_0x2edde60 .part L_0x2eddcd0, 0, 1;
S_0x2ec30a0 .scope module, "Contador_index" "Contador" 3 104, 5 1 0, S_0x2e950f0;
 .timescale -9 -12;
    .port_info 0 /INPUT 1 "clk";
    .port_info 1 /INPUT 1 "reset";
    .port_info 2 /INPUT 1 "inc";
    .port_info 3 /OUTPUT 2 "outc";
    .port_info 4 /OUTPUT 1 "zero";
P_0x2ec3280 .param/l "width" 0 5 2, +C4<00000000000000000000000000000001>;
v0x2ec3460_0 .net *"_ivl_0", 31 0, L_0x2eddf50;  1 drivers
L_0x750b0771f570 .functor BUFT 1, C4<00>, C4<0>, C4<0>, C4<0>;
v0x2ec3560_0 .net/2s *"_ivl_10", 1 0, L_0x750b0771f570;  1 drivers
v0x2ec3640_0 .net *"_ivl_12", 1 0, L_0x2ede180;  1 drivers
L_0x750b0771f498 .functor BUFT 1, C4<000000000000000000000000000000>, C4<0>, C4<0>, C4<0>;
v0x2ec3730_0 .net *"_ivl_3", 29 0, L_0x750b0771f498;  1 drivers
L_0x750b0771f4e0 .functor BUFT 1, C4<00000000000000000000000000000000>, C4<0>, C4<0>, C4<0>;
v0x2ec3810_0 .net/2u *"_ivl_4", 31 0, L_0x750b0771f4e0;  1 drivers
v0x2ec3940_0 .net *"_ivl_6", 0 0, L_0x2ede040;  1 drivers
L_0x750b0771f528 .functor BUFT 1, C4<01>, C4<0>, C4<0>, C4<0>;
v0x2ec3a00_0 .net/2s *"_ivl_8", 1 0, L_0x750b0771f528;  1 drivers
v0x2ec3ae0_0 .net "clk", 0 0, v0x2eca560_0;  alias, 1 drivers
v0x2ec3b80_0 .net "inc", 0 0, v0x2ec64c0_0;  alias, 1 drivers
v0x2ec3c40_0 .var "outc", 1 0;
v0x2ec3d20_0 .net "reset", 0 0, v0x2ec6b70_0;  alias, 1 drivers
v0x2ec3de0_0 .net "zero", 0 0, L_0x2ede310;  alias, 1 drivers
L_0x2eddf50 .concat [ 2 30 0 0], v0x2ec3c40_0, L_0x750b0771f498;
L_0x2ede040 .cmp/eq 32, L_0x2eddf50, L_0x750b0771f4e0;
L_0x2ede180 .functor MUXZ 2, L_0x750b0771f570, L_0x750b0771f528, L_0x2ede040, C4<>;
L_0x2ede310 .part L_0x2ede180, 0, 1;
S_0x2ec3f40 .scope module, "Contador_row" "Contador" 3 81, 5 1 0, S_0x2e950f0;
 .timescale -9 -12;
    .port_info 0 /INPUT 1 "clk";
    .port_info 1 /INPUT 1 "reset";
    .port_info 2 /INPUT 1 "inc";
    .port_info 3 /OUTPUT 5 "outc";
    .port_info 4 /OUTPUT 1 "zero";
P_0x2ec40d0 .param/l "width" 0 5 2, +C4<00000000000000000000000000000100>;
v0x2ec42e0_0 .net *"_ivl_0", 31 0, L_0x2edd070;  1 drivers
L_0x750b0771f210 .functor BUFT 1, C4<00>, C4<0>, C4<0>, C4<0>;
v0x2ec43e0_0 .net/2s *"_ivl_10", 1 0, L_0x750b0771f210;  1 drivers
v0x2ec44c0_0 .net *"_ivl_12", 1 0, L_0x2edd330;  1 drivers
L_0x750b0771f138 .functor BUFT 1, C4<000000000000000000000000000>, C4<0>, C4<0>, C4<0>;
v0x2ec45b0_0 .net *"_ivl_3", 26 0, L_0x750b0771f138;  1 drivers
L_0x750b0771f180 .functor BUFT 1, C4<00000000000000000000000000000000>, C4<0>, C4<0>, C4<0>;
v0x2ec4690_0 .net/2u *"_ivl_4", 31 0, L_0x750b0771f180;  1 drivers
v0x2ec47c0_0 .net *"_ivl_6", 0 0, L_0x2edd1f0;  1 drivers
L_0x750b0771f1c8 .functor BUFT 1, C4<01>, C4<0>, C4<0>, C4<0>;
v0x2ec4880_0 .net/2s *"_ivl_8", 1 0, L_0x750b0771f1c8;  1 drivers
v0x2ec4960_0 .net "clk", 0 0, v0x2eca560_0;  alias, 1 drivers
v0x2ec4a00_0 .net "inc", 0 0, v0x2ec65b0_0;  alias, 1 drivers
v0x2ec4b50_0 .var "outc", 4 0;
v0x2ec4c30_0 .net "reset", 0 0, v0x2ec6c40_0;  alias, 1 drivers
v0x2ec4cf0_0 .net "zero", 0 0, L_0x2edd4c0;  alias, 1 drivers
L_0x2edd070 .concat [ 5 27 0 0], v0x2ec4b50_0, L_0x750b0771f138;
L_0x2edd1f0 .cmp/eq 32, L_0x2edd070, L_0x750b0771f180;
L_0x2edd330 .functor MUXZ 2, L_0x750b0771f210, L_0x750b0771f1c8, L_0x2edd1f0, C4<>;
L_0x2edd4c0 .part L_0x2edd330, 0, 1;
S_0x2ec4e50 .scope module, "Multiplexor0" "Multiplexor" 3 133, 6 1 0, S_0x2e950f0;
 .timescale -9 -12;
    .port_info 0 /INPUT 24 "in0";
    .port_info 1 /INPUT 2 "sel";
    .port_info 2 /OUTPUT 6 "out0";
v0x2ec5040_0 .net "in0", 23 0, v0x2ec87c0_0;  alias, 1 drivers
v0x2ec5140_0 .var "out0", 5 0;
v0x2ec5220_0 .net "sel", 1 0, v0x2ec3c40_0;  alias, 1 drivers
E_0x2e1af10 .event anyedge, v0x2ec3c40_0, v0x2ec5040_0;
S_0x2ec5350 .scope module, "control_video0" "control_video" 3 157, 7 1 0, S_0x2e950f0;
 .timescale -9 -12;
    .port_info 0 /INPUT 1 "clk";
    .port_info 1 /INPUT 1 "init";
    .port_info 2 /INPUT 1 "rst";
    .port_info 3 /INPUT 1 "ZR";
    .port_info 4 /INPUT 1 "ZC";
    .port_info 5 /INPUT 1 "ZD";
    .port_info 6 /INPUT 1 "ZI";
    .port_info 7 /INPUT 1 "ZFRAME";
    .port_info 8 /OUTPUT 1 "RST_R";
    .port_info 9 /OUTPUT 1 "RST_C";
    .port_info 10 /OUTPUT 1 "RST_D";
    .port_info 11 /OUTPUT 1 "RST_I";
    .port_info 12 /OUTPUT 1 "RST_F";
    .port_info 13 /OUTPUT 1 "INC_R";
    .port_info 14 /OUTPUT 1 "INC_C";
    .port_info 15 /OUTPUT 1 "INC_D";
    .port_info 16 /OUTPUT 1 "INC_I";
    .port_info 17 /OUTPUT 1 "INC_F";
    .port_info 18 /OUTPUT 1 "CHANGE";
    .port_info 19 /OUTPUT 1 "LD";
    .port_info 20 /OUTPUT 1 "SHD";
    .port_info 21 /OUTPUT 1 "LATCH";
    .port_info 22 /OUTPUT 1 "NOE";
    .port_info 23 /OUTPUT 1 "PX_CLK_EN";
P_0x2ec54e0 .param/l "DELAY_ROW" 0 7 36, C4<0100>;
P_0x2ec5520 .param/l "FRAME_TARGET" 0 7 52, +C4<00000000000000000000000000011001>;
P_0x2ec5560 .param/l "GET_PIXEL" 0 7 33, C4<0001>;
P_0x2ec55a0 .param/l "INC_COL" 0 7 34, C4<0010>;
P_0x2ec55e0 .param/l "INC_ROW" 0 7 39, C4<0111>;
P_0x2ec5620 .param/l "NEXT_BIT" 0 7 37, C4<0101>;
P_0x2ec5660 .param/l "NEXT_DELAY" 0 7 38, C4<0110>;
P_0x2ec56a0 .param/l "NEXT_FRAME" 0 7 41, C4<1001>;
P_0x2ec56e0 .param/l "READY_FRAME" 0 7 40, C4<1000>;
P_0x2ec5720 .param/l "SEND_ROW" 0 7 35, C4<0011>;
P_0x2ec5760 .param/l "START" 0 7 32, C4<0000>;
P_0x2ec57a0 .param/l "WAIT_FRAME" 0 7 42, C4<1010>;
v0x2ec6120_0 .var "CHANGE", 0 0;
v0x2ec6200_0 .var "INC_C", 0 0;
v0x2ec62f0_0 .var "INC_D", 0 0;
v0x2ec63f0_0 .var "INC_F", 0 0;
v0x2ec64c0_0 .var "INC_I", 0 0;
v0x2ec65b0_0 .var "INC_R", 0 0;
v0x2ec6680_0 .var "LATCH", 0 0;
v0x2ec6720_0 .var "LD", 0 0;
v0x2ec67c0_0 .var "NOE", 0 0;
v0x2ec6860_0 .var "PX_CLK_EN", 0 0;
v0x2ec6900_0 .var "RST_C", 0 0;
v0x2ec69d0_0 .var "RST_D", 0 0;
v0x2ec6aa0_0 .var "RST_F", 0 0;
v0x2ec6b70_0 .var "RST_I", 0 0;
v0x2ec6c40_0 .var "RST_R", 0 0;
v0x2ec6d10_0 .var "SHD", 0 0;
v0x2ec6db0_0 .net "ZC", 0 0, L_0x2edd9b0;  alias, 1 drivers
v0x2ec6e80_0 .net "ZD", 0 0, v0x2e8dfb0_0;  alias, 1 drivers
v0x2ec6f50_0 .net "ZFRAME", 0 0, L_0x2ede7c0;  alias, 1 drivers
v0x2ec7020_0 .net "ZI", 0 0, L_0x2ede310;  alias, 1 drivers
v0x2ec70f0_0 .net "ZR", 0 0, L_0x2edd4c0;  alias, 1 drivers
v0x2ec71c0_0 .net "clk", 0 0, v0x2eca560_0;  alias, 1 drivers
v0x2ec7260_0 .var "frame_counter", 7 0;
L_0x750b0771f7b0 .functor BUFT 1, C4<1>, C4<0>, C4<0>, C4<0>;
v0x2ec7300_0 .net "init", 0 0, L_0x750b0771f7b0;  1 drivers
v0x2ec73a0_0 .net "rst", 0 0, L_0x2edec70;  1 drivers
v0x2ec7440_0 .var "state", 9 0;
E_0x2ea7e80 .event anyedge, v0x2ec7440_0;
E_0x2ea7ec0 .event posedge, v0x2ec0f80_0;
S_0x2ec77f0 .scope module, "lsr_led0" "Lsr_led" 3 120, 8 1 0, S_0x2e950f0;
 .timescale -9 -12;
    .port_info 0 /INPUT 1 "clk";
    .port_info 1 /INPUT 1 "shift";
    .port_info 2 /INPUT 1 "load";
    .port_info 3 /OUTPUT 11 "s_A";
P_0x2ec7980 .param/l "init_value" 0 8 2, +C4<00000000000000000000000000001010>;
P_0x2ec79c0 .param/l "width" 0 8 3, +C4<00000000000000000000000000001010>;
v0x2ec7bd0_0 .net "clk", 0 0, v0x2eca560_0;  alias, 1 drivers
v0x2ec7c90_0 .net "load", 0 0, v0x2ec6720_0;  alias, 1 drivers
v0x2ec7d80_0 .var "s_A", 10 0;
v0x2ec7e80_0 .net "shift", 0 0, v0x2ec6d10_0;  alias, 1 drivers
S_0x2ec7f80 .scope module, "memory_doble0" "memory_doble" 3 147, 9 1 0, S_0x2e950f0;
 .timescale -9 -12;
    .port_info 0 /INPUT 1 "clk";
    .port_info 1 /INPUT 1 "rd";
    .port_info 2 /INPUT 1 "wr";
    .port_info 3 /INPUT 1 "CHANGE";
    .port_info 4 /INPUT 12 "address";
    .port_info 5 /INPUT 24 "wdata";
    .port_info 6 /OUTPUT 24 "rdata";
v0x2ec8240_0 .net "CHANGE", 0 0, v0x2ec6120_0;  alias, 1 drivers
v0x2ec8300 .array "MEM0", 2047 0, 23 0;
v0x2ec83a0 .array "MEM1", 2047 0, 23 0;
v0x2ec8470_0 .var "activar_memoria", 0 0;
v0x2ec8530_0 .net "address", 11 0, L_0x2ecc940;  alias, 1 drivers
v0x2ec8660_0 .net "clk", 0 0, v0x2eca560_0;  alias, 1 drivers
L_0x750b0771f720 .functor BUFT 1, C4<1>, C4<0>, C4<0>, C4<0>;
v0x2ec8700_0 .net "rd", 0 0, L_0x750b0771f720;  1 drivers
v0x2ec87c0_0 .var "rdata", 23 0;
v0x2ec8880_0 .net "wdata", 23 0, v0x2ec9230_0;  alias, 1 drivers
L_0x750b0771f768 .functor BUFT 1, C4<1>, C4<0>, C4<0>, C4<0>;
v0x2ec89d0_0 .net "wr", 0 0, L_0x750b0771f768;  1 drivers
S_0x2ec8bb0 .scope module, "memory_principal0" "memory_principal" 3 139, 10 1 0, S_0x2e950f0;
 .timescale -9 -12;
    .port_info 0 /INPUT 1 "clk";
    .port_info 1 /INPUT 1 "rd_image";
    .port_info 2 /INPUT 16 "address_image";
    .port_info 3 /OUTPUT 24 "data_out";
P_0x2df8510 .param/l "FRAME_PIXELS" 0 10 3, +C4<00000000000000000000100000000000>;
P_0x2df8550 .param/l "N_FRAMES" 0 10 2, +C4<00000000000000000000000000011000>;
P_0x2df8590 .param/l "TOTAL_PIXELS" 0 10 4, +C4<0000000000000000000000000000000000000000000000001100000000000000>;
v0x2ec8fa0 .array "MEM", 49151 0, 23 0;
v0x2ec9080_0 .net "address_image", 15 0, L_0x2edce00;  alias, 1 drivers
v0x2ec9160_0 .net "clk", 0 0, v0x2eca560_0;  alias, 1 drivers
v0x2ec9230_0 .var "data_out", 23 0;
L_0x750b0771f6d8 .functor BUFT 1, C4<1>, C4<0>, C4<0>, C4<0>;
v0x2ec9300_0 .net "rd_image", 0 0, L_0x750b0771f6d8;  1 drivers
    .scope S_0x2ec3f40;
T_0 ;
    %wait E_0x2e44c20;
    %load/vec4 v0x2ec4c30_0;
    %inv;
    %flag_set/vec4 8;
    %jmp/0xz  T_0.0, 8;
    %pushi/vec4 0, 0, 5;
    %assign/vec4 v0x2ec4b50_0, 0;
    %jmp T_0.1;
T_0.0 ;
    %load/vec4 v0x2ec4a00_0;
    %flag_set/vec4 8;
    %jmp/0xz  T_0.2, 8;
    %load/vec4 v0x2ec4b50_0;
    %addi 1, 0, 5;
    %assign/vec4 v0x2ec4b50_0, 0;
T_0.2 ;
T_0.1 ;
    %jmp T_0;
    .thread T_0;
    .scope S_0x2ec1400;
T_1 ;
    %wait E_0x2e44c20;
    %load/vec4 v0x2ec1fc0_0;
    %inv;
    %flag_set/vec4 8;
    %jmp/0xz  T_1.0, 8;
    %pushi/vec4 0, 0, 6;
    %assign/vec4 v0x2ec1ee0_0, 0;
    %jmp T_1.1;
T_1.0 ;
    %load/vec4 v0x2ec1e40_0;
    %flag_set/vec4 8;
    %jmp/0xz  T_1.2, 8;
    %load/vec4 v0x2ec1ee0_0;
    %addi 1, 0, 6;
    %assign/vec4 v0x2ec1ee0_0, 0;
T_1.2 ;
T_1.1 ;
    %jmp T_1;
    .thread T_1;
    .scope S_0x2ec2210;
T_2 ;
    %wait E_0x2e44c20;
    %load/vec4 v0x2ec2ea0_0;
    %inv;
    %flag_set/vec4 8;
    %jmp/0xz  T_2.0, 8;
    %pushi/vec4 0, 0, 11;
    %assign/vec4 v0x2ec2de0_0, 0;
    %jmp T_2.1;
T_2.0 ;
    %load/vec4 v0x2ec2d20_0;
    %flag_set/vec4 8;
    %jmp/0xz  T_2.2, 8;
    %load/vec4 v0x2ec2de0_0;
    %addi 1, 0, 11;
    %assign/vec4 v0x2ec2de0_0, 0;
T_2.2 ;
T_2.1 ;
    %jmp T_2;
    .thread T_2;
    .scope S_0x2ec30a0;
T_3 ;
    %wait E_0x2e44c20;
    %load/vec4 v0x2ec3d20_0;
    %inv;
    %flag_set/vec4 8;
    %jmp/0xz  T_3.0, 8;
    %pushi/vec4 0, 0, 2;
    %assign/vec4 v0x2ec3c40_0, 0;
    %jmp T_3.1;
T_3.0 ;
    %load/vec4 v0x2ec3b80_0;
    %flag_set/vec4 8;
    %jmp/0xz  T_3.2, 8;
    %load/vec4 v0x2ec3c40_0;
    %addi 1, 0, 2;
    %assign/vec4 v0x2ec3c40_0, 0;
T_3.2 ;
T_3.1 ;
    %jmp T_3;
    .thread T_3;
    .scope S_0x2ec0860;
T_4 ;
    %wait E_0x2e44c20;
    %load/vec4 v0x2ec11e0_0;
    %inv;
    %flag_set/vec4 8;
    %jmp/0xz  T_4.0, 8;
    %pushi/vec4 0, 0, 6;
    %assign/vec4 v0x2ec1100_0, 0;
    %jmp T_4.1;
T_4.0 ;
    %load/vec4 v0x2ec1040_0;
    %flag_set/vec4 8;
    %jmp/0xz  T_4.2, 8;
    %load/vec4 v0x2ec1100_0;
    %addi 1, 0, 6;
    %assign/vec4 v0x2ec1100_0, 0;
T_4.2 ;
T_4.1 ;
    %jmp T_4;
    .thread T_4;
    .scope S_0x2ec77f0;
T_5 ;
    %wait E_0x2e44c20;
    %load/vec4 v0x2ec7c90_0;
    %flag_set/vec4 8;
    %jmp/0xz  T_5.0, 8;
    %pushi/vec4 10, 0, 11;
    %assign/vec4 v0x2ec7d80_0, 0;
    %jmp T_5.1;
T_5.0 ;
    %load/vec4 v0x2ec7e80_0;
    %flag_set/vec4 8;
    %jmp/0xz  T_5.2, 8;
    %load/vec4 v0x2ec7d80_0;
    %ix/load 4, 1, 0;
    %flag_set/imm 4, 0;
    %shiftl 4;
    %assign/vec4 v0x2ec7d80_0, 0;
    %jmp T_5.3;
T_5.2 ;
    %load/vec4 v0x2ec7d80_0;
    %assign/vec4 v0x2ec7d80_0, 0;
T_5.3 ;
T_5.1 ;
    %jmp T_5;
    .thread T_5;
    .scope S_0x2e81070;
T_6 ;
    %wait E_0x2e44900;
    %load/vec4 v0x2e93e50_0;
    %load/vec4 v0x2e94b70_0;
    %cmp/e;
    %jmp/0xz  T_6.0, 4;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x2e8dfb0_0, 0, 1;
    %jmp T_6.1;
T_6.0 ;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2e8dfb0_0, 0, 1;
T_6.1 ;
    %jmp T_6;
    .thread T_6, $push;
    .scope S_0x2ec4e50;
T_7 ;
    %wait E_0x2e1af10;
    %load/vec4 v0x2ec5220_0;
    %dup/vec4;
    %pushi/vec4 0, 0, 2;
    %cmp/u;
    %jmp/1 T_7.0, 6;
    %dup/vec4;
    %pushi/vec4 1, 0, 2;
    %cmp/u;
    %jmp/1 T_7.1, 6;
    %dup/vec4;
    %pushi/vec4 2, 0, 2;
    %cmp/u;
    %jmp/1 T_7.2, 6;
    %dup/vec4;
    %pushi/vec4 3, 0, 2;
    %cmp/u;
    %jmp/1 T_7.3, 6;
    %load/vec4 v0x2ec5040_0;
    %parti/s 1, 20, 6;
    %load/vec4 v0x2ec5040_0;
    %parti/s 1, 16, 6;
    %concat/vec4; draw_concat_vec4
    %load/vec4 v0x2ec5040_0;
    %parti/s 1, 12, 5;
    %concat/vec4; draw_concat_vec4
    %load/vec4 v0x2ec5040_0;
    %parti/s 1, 8, 5;
    %concat/vec4; draw_concat_vec4
    %load/vec4 v0x2ec5040_0;
    %parti/s 1, 4, 4;
    %concat/vec4; draw_concat_vec4
    %load/vec4 v0x2ec5040_0;
    %parti/s 1, 0, 2;
    %concat/vec4; draw_concat_vec4
    %store/vec4 v0x2ec5140_0, 0, 6;
    %jmp T_7.5;
T_7.0 ;
    %load/vec4 v0x2ec5040_0;
    %parti/s 1, 20, 6;
    %load/vec4 v0x2ec5040_0;
    %parti/s 1, 16, 6;
    %concat/vec4; draw_concat_vec4
    %load/vec4 v0x2ec5040_0;
    %parti/s 1, 12, 5;
    %concat/vec4; draw_concat_vec4
    %load/vec4 v0x2ec5040_0;
    %parti/s 1, 8, 5;
    %concat/vec4; draw_concat_vec4
    %load/vec4 v0x2ec5040_0;
    %parti/s 1, 4, 4;
    %concat/vec4; draw_concat_vec4
    %load/vec4 v0x2ec5040_0;
    %parti/s 1, 0, 2;
    %concat/vec4; draw_concat_vec4
    %store/vec4 v0x2ec5140_0, 0, 6;
    %jmp T_7.5;
T_7.1 ;
    %load/vec4 v0x2ec5040_0;
    %parti/s 1, 21, 6;
    %load/vec4 v0x2ec5040_0;
    %parti/s 1, 17, 6;
    %concat/vec4; draw_concat_vec4
    %load/vec4 v0x2ec5040_0;
    %parti/s 1, 13, 5;
    %concat/vec4; draw_concat_vec4
    %load/vec4 v0x2ec5040_0;
    %parti/s 1, 9, 5;
    %concat/vec4; draw_concat_vec4
    %load/vec4 v0x2ec5040_0;
    %parti/s 1, 5, 4;
    %concat/vec4; draw_concat_vec4
    %load/vec4 v0x2ec5040_0;
    %parti/s 1, 1, 2;
    %concat/vec4; draw_concat_vec4
    %store/vec4 v0x2ec5140_0, 0, 6;
    %jmp T_7.5;
T_7.2 ;
    %load/vec4 v0x2ec5040_0;
    %parti/s 1, 22, 6;
    %load/vec4 v0x2ec5040_0;
    %parti/s 1, 18, 6;
    %concat/vec4; draw_concat_vec4
    %load/vec4 v0x2ec5040_0;
    %parti/s 1, 14, 5;
    %concat/vec4; draw_concat_vec4
    %load/vec4 v0x2ec5040_0;
    %parti/s 1, 10, 5;
    %concat/vec4; draw_concat_vec4
    %load/vec4 v0x2ec5040_0;
    %parti/s 1, 6, 4;
    %concat/vec4; draw_concat_vec4
    %load/vec4 v0x2ec5040_0;
    %parti/s 1, 2, 3;
    %concat/vec4; draw_concat_vec4
    %store/vec4 v0x2ec5140_0, 0, 6;
    %jmp T_7.5;
T_7.3 ;
    %load/vec4 v0x2ec5040_0;
    %parti/s 1, 23, 6;
    %load/vec4 v0x2ec5040_0;
    %parti/s 1, 19, 6;
    %concat/vec4; draw_concat_vec4
    %load/vec4 v0x2ec5040_0;
    %parti/s 1, 15, 5;
    %concat/vec4; draw_concat_vec4
    %load/vec4 v0x2ec5040_0;
    %parti/s 1, 11, 5;
    %concat/vec4; draw_concat_vec4
    %load/vec4 v0x2ec5040_0;
    %parti/s 1, 7, 4;
    %concat/vec4; draw_concat_vec4
    %load/vec4 v0x2ec5040_0;
    %parti/s 1, 3, 3;
    %concat/vec4; draw_concat_vec4
    %store/vec4 v0x2ec5140_0, 0, 6;
    %jmp T_7.5;
T_7.5 ;
    %pop/vec4 1;
    %jmp T_7;
    .thread T_7, $push;
    .scope S_0x2ec8bb0;
T_8 ;
    %vpi_call 10 15 "$readmemh", "./video.hex", v0x2ec8fa0 {0 0 0};
    %end;
    .thread T_8;
    .scope S_0x2ec8bb0;
T_9 ;
    %wait E_0x2e44c20;
    %load/vec4 v0x2ec9300_0;
    %flag_set/vec4 8;
    %jmp/0xz  T_9.0, 8;
    %load/vec4 v0x2ec9080_0;
    %pad/u 17;
    %ix/vec4 4;
    %load/vec4a v0x2ec8fa0, 4;
    %assign/vec4 v0x2ec9230_0, 0;
T_9.0 ;
    %jmp T_9;
    .thread T_9;
    .scope S_0x2ec7f80;
T_10 ;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec8470_0, 0, 1;
    %end;
    .thread T_10;
    .scope S_0x2ec7f80;
T_11 ;
    %wait E_0x2e44c20;
    %load/vec4 v0x2ec8240_0;
    %flag_set/vec4 8;
    %jmp/0xz  T_11.0, 8;
    %load/vec4 v0x2ec8470_0;
    %inv;
    %assign/vec4 v0x2ec8470_0, 0;
T_11.0 ;
    %jmp T_11;
    .thread T_11;
    .scope S_0x2ec7f80;
T_12 ;
    %wait E_0x2e44c20;
    %load/vec4 v0x2ec89d0_0;
    %flag_set/vec4 8;
    %jmp/0xz  T_12.0, 8;
    %load/vec4 v0x2ec8470_0;
    %cmpi/e 0, 0, 1;
    %jmp/0xz  T_12.2, 4;
    %load/vec4 v0x2ec8880_0;
    %load/vec4 v0x2ec8530_0;
    %pad/u 13;
    %ix/vec4 3;
    %ix/load 4, 0, 0; Constant delay
    %assign/vec4/a/d v0x2ec83a0, 0, 4;
    %jmp T_12.3;
T_12.2 ;
    %load/vec4 v0x2ec8880_0;
    %load/vec4 v0x2ec8530_0;
    %pad/u 13;
    %ix/vec4 3;
    %ix/load 4, 0, 0; Constant delay
    %assign/vec4/a/d v0x2ec8300, 0, 4;
T_12.3 ;
T_12.0 ;
    %load/vec4 v0x2ec8700_0;
    %flag_set/vec4 8;
    %jmp/0xz  T_12.4, 8;
    %load/vec4 v0x2ec8470_0;
    %cmpi/e 0, 0, 1;
    %jmp/0xz  T_12.6, 4;
    %load/vec4 v0x2ec8530_0;
    %pad/u 13;
    %ix/vec4 4;
    %load/vec4a v0x2ec8300, 4;
    %assign/vec4 v0x2ec87c0_0, 0;
    %jmp T_12.7;
T_12.6 ;
    %load/vec4 v0x2ec8530_0;
    %pad/u 13;
    %ix/vec4 4;
    %load/vec4a v0x2ec83a0, 4;
    %assign/vec4 v0x2ec87c0_0, 0;
T_12.7 ;
T_12.4 ;
    %jmp T_12;
    .thread T_12;
    .scope S_0x2ec5350;
T_13 ;
    %wait E_0x2ea7ec0;
    %load/vec4 v0x2ec73a0_0;
    %flag_set/vec4 8;
    %jmp/0xz  T_13.0, 8;
    %pushi/vec4 0, 0, 10;
    %store/vec4 v0x2ec7440_0, 0, 10;
    %pushi/vec4 0, 0, 8;
    %store/vec4 v0x2ec7260_0, 0, 8;
    %jmp T_13.1;
T_13.0 ;
    %load/vec4 v0x2ec7440_0;
    %dup/vec4;
    %pushi/vec4 0, 0, 10;
    %cmp/u;
    %jmp/1 T_13.2, 6;
    %dup/vec4;
    %pushi/vec4 1, 0, 10;
    %cmp/u;
    %jmp/1 T_13.3, 6;
    %dup/vec4;
    %pushi/vec4 2, 0, 10;
    %cmp/u;
    %jmp/1 T_13.4, 6;
    %dup/vec4;
    %pushi/vec4 3, 0, 10;
    %cmp/u;
    %jmp/1 T_13.5, 6;
    %dup/vec4;
    %pushi/vec4 4, 0, 10;
    %cmp/u;
    %jmp/1 T_13.6, 6;
    %dup/vec4;
    %pushi/vec4 5, 0, 10;
    %cmp/u;
    %jmp/1 T_13.7, 6;
    %dup/vec4;
    %pushi/vec4 6, 0, 10;
    %cmp/u;
    %jmp/1 T_13.8, 6;
    %dup/vec4;
    %pushi/vec4 7, 0, 10;
    %cmp/u;
    %jmp/1 T_13.9, 6;
    %dup/vec4;
    %pushi/vec4 8, 0, 10;
    %cmp/u;
    %jmp/1 T_13.10, 6;
    %dup/vec4;
    %pushi/vec4 10, 0, 10;
    %cmp/u;
    %jmp/1 T_13.11, 6;
    %dup/vec4;
    %pushi/vec4 9, 0, 10;
    %cmp/u;
    %jmp/1 T_13.12, 6;
    %pushi/vec4 0, 0, 10;
    %store/vec4 v0x2ec7440_0, 0, 10;
    %jmp T_13.14;
T_13.2 ;
    %pushi/vec4 0, 0, 8;
    %store/vec4 v0x2ec7260_0, 0, 8;
    %load/vec4 v0x2ec7300_0;
    %flag_set/vec4 8;
    %jmp/0xz  T_13.15, 8;
    %pushi/vec4 1, 0, 10;
    %store/vec4 v0x2ec7440_0, 0, 10;
    %jmp T_13.16;
T_13.15 ;
    %pushi/vec4 0, 0, 10;
    %store/vec4 v0x2ec7440_0, 0, 10;
T_13.16 ;
    %jmp T_13.14;
T_13.3 ;
    %pushi/vec4 2, 0, 10;
    %store/vec4 v0x2ec7440_0, 0, 10;
    %jmp T_13.14;
T_13.4 ;
    %load/vec4 v0x2ec6db0_0;
    %flag_set/vec4 8;
    %jmp/0xz  T_13.17, 8;
    %pushi/vec4 3, 0, 10;
    %store/vec4 v0x2ec7440_0, 0, 10;
    %jmp T_13.18;
T_13.17 ;
    %pushi/vec4 2, 0, 10;
    %store/vec4 v0x2ec7440_0, 0, 10;
T_13.18 ;
    %jmp T_13.14;
T_13.5 ;
    %pushi/vec4 4, 0, 10;
    %store/vec4 v0x2ec7440_0, 0, 10;
    %jmp T_13.14;
T_13.6 ;
    %load/vec4 v0x2ec6e80_0;
    %flag_set/vec4 8;
    %jmp/0xz  T_13.19, 8;
    %pushi/vec4 5, 0, 10;
    %store/vec4 v0x2ec7440_0, 0, 10;
    %jmp T_13.20;
T_13.19 ;
    %pushi/vec4 4, 0, 10;
    %store/vec4 v0x2ec7440_0, 0, 10;
T_13.20 ;
    %jmp T_13.14;
T_13.7 ;
    %pushi/vec4 6, 0, 10;
    %store/vec4 v0x2ec7440_0, 0, 10;
    %jmp T_13.14;
T_13.8 ;
    %load/vec4 v0x2ec7020_0;
    %flag_set/vec4 8;
    %jmp/0xz  T_13.21, 8;
    %pushi/vec4 7, 0, 10;
    %store/vec4 v0x2ec7440_0, 0, 10;
    %jmp T_13.22;
T_13.21 ;
    %pushi/vec4 1, 0, 10;
    %store/vec4 v0x2ec7440_0, 0, 10;
T_13.22 ;
    %jmp T_13.14;
T_13.9 ;
    %pushi/vec4 8, 0, 10;
    %store/vec4 v0x2ec7440_0, 0, 10;
    %jmp T_13.14;
T_13.10 ;
    %load/vec4 v0x2ec70f0_0;
    %flag_set/vec4 8;
    %jmp/0xz  T_13.23, 8;
    %pushi/vec4 10, 0, 10;
    %store/vec4 v0x2ec7440_0, 0, 10;
    %jmp T_13.24;
T_13.23 ;
    %pushi/vec4 1, 0, 10;
    %store/vec4 v0x2ec7440_0, 0, 10;
T_13.24 ;
    %jmp T_13.14;
T_13.11 ;
    %load/vec4 v0x2ec7260_0;
    %pad/u 32;
    %cmpi/u 25, 0, 32;
    %flag_inv 5; GE is !LT
    %jmp/0xz  T_13.25, 5;
    %pushi/vec4 0, 0, 8;
    %store/vec4 v0x2ec7260_0, 0, 8;
    %pushi/vec4 9, 0, 10;
    %store/vec4 v0x2ec7440_0, 0, 10;
    %jmp T_13.26;
T_13.25 ;
    %load/vec4 v0x2ec7260_0;
    %addi 1, 0, 8;
    %store/vec4 v0x2ec7260_0, 0, 8;
    %pushi/vec4 1, 0, 10;
    %store/vec4 v0x2ec7440_0, 0, 10;
T_13.26 ;
    %jmp T_13.14;
T_13.12 ;
    %pushi/vec4 0, 0, 8;
    %store/vec4 v0x2ec7260_0, 0, 8;
    %load/vec4 v0x2ec6f50_0;
    %flag_set/vec4 8;
    %jmp/0xz  T_13.27, 8;
    %pushi/vec4 0, 0, 10;
    %store/vec4 v0x2ec7440_0, 0, 10;
    %jmp T_13.28;
T_13.27 ;
    %pushi/vec4 1, 0, 10;
    %store/vec4 v0x2ec7440_0, 0, 10;
T_13.28 ;
    %jmp T_13.14;
T_13.14 ;
    %pop/vec4 1;
T_13.1 ;
    %jmp T_13;
    .thread T_13;
    .scope S_0x2ec5350;
T_14 ;
    %wait E_0x2ea7e80;
    %load/vec4 v0x2ec7440_0;
    %dup/vec4;
    %pushi/vec4 0, 0, 10;
    %cmp/u;
    %jmp/1 T_14.0, 6;
    %dup/vec4;
    %pushi/vec4 1, 0, 10;
    %cmp/u;
    %jmp/1 T_14.1, 6;
    %dup/vec4;
    %pushi/vec4 2, 0, 10;
    %cmp/u;
    %jmp/1 T_14.2, 6;
    %dup/vec4;
    %pushi/vec4 3, 0, 10;
    %cmp/u;
    %jmp/1 T_14.3, 6;
    %dup/vec4;
    %pushi/vec4 4, 0, 10;
    %cmp/u;
    %jmp/1 T_14.4, 6;
    %dup/vec4;
    %pushi/vec4 5, 0, 10;
    %cmp/u;
    %jmp/1 T_14.5, 6;
    %dup/vec4;
    %pushi/vec4 6, 0, 10;
    %cmp/u;
    %jmp/1 T_14.6, 6;
    %dup/vec4;
    %pushi/vec4 7, 0, 10;
    %cmp/u;
    %jmp/1 T_14.7, 6;
    %dup/vec4;
    %pushi/vec4 8, 0, 10;
    %cmp/u;
    %jmp/1 T_14.8, 6;
    %dup/vec4;
    %pushi/vec4 10, 0, 10;
    %cmp/u;
    %jmp/1 T_14.9, 6;
    %dup/vec4;
    %pushi/vec4 9, 0, 10;
    %cmp/u;
    %jmp/1 T_14.10, 6;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec6c40_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec6900_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec69d0_0, 0, 1;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x2ec6b70_0, 0, 1;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x2ec6aa0_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec65b0_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec6200_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec62f0_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec64c0_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec63f0_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec6720_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec6d10_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec6120_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec6680_0, 0, 1;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x2ec67c0_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec6860_0, 0, 1;
    %jmp T_14.12;
T_14.0 ;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec6c40_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec6900_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec69d0_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec6b70_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec6aa0_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec65b0_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec6200_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec62f0_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec64c0_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec63f0_0, 0, 1;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x2ec6720_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec6d10_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec6120_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec6680_0, 0, 1;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x2ec67c0_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec6860_0, 0, 1;
    %jmp T_14.12;
T_14.1 ;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x2ec6c40_0, 0, 1;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x2ec6900_0, 0, 1;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x2ec69d0_0, 0, 1;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x2ec6b70_0, 0, 1;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x2ec6aa0_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec65b0_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec6200_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec62f0_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec64c0_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec63f0_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec6720_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec6d10_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec6120_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec6680_0, 0, 1;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x2ec67c0_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec6860_0, 0, 1;
    %jmp T_14.12;
T_14.2 ;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x2ec6c40_0, 0, 1;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x2ec6900_0, 0, 1;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x2ec69d0_0, 0, 1;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x2ec6b70_0, 0, 1;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x2ec6aa0_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec65b0_0, 0, 1;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x2ec6200_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec62f0_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec64c0_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec63f0_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec6720_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec6d10_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec6120_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec6680_0, 0, 1;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x2ec67c0_0, 0, 1;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x2ec6860_0, 0, 1;
    %jmp T_14.12;
T_14.3 ;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x2ec6c40_0, 0, 1;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x2ec6900_0, 0, 1;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x2ec69d0_0, 0, 1;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x2ec6b70_0, 0, 1;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x2ec6aa0_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec65b0_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec6200_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec62f0_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec64c0_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec63f0_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec6720_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec6d10_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec6120_0, 0, 1;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x2ec6680_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec67c0_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec6860_0, 0, 1;
    %jmp T_14.12;
T_14.4 ;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x2ec6c40_0, 0, 1;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x2ec6900_0, 0, 1;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x2ec69d0_0, 0, 1;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x2ec6b70_0, 0, 1;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x2ec6aa0_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec65b0_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec6200_0, 0, 1;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x2ec62f0_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec64c0_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec63f0_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec6720_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec6d10_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec6120_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec6680_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec67c0_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec6860_0, 0, 1;
    %jmp T_14.12;
T_14.5 ;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x2ec6c40_0, 0, 1;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x2ec6900_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec69d0_0, 0, 1;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x2ec6b70_0, 0, 1;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x2ec6aa0_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec65b0_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec6200_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec62f0_0, 0, 1;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x2ec64c0_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec63f0_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec6720_0, 0, 1;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x2ec6d10_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec6120_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec6680_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec67c0_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec6860_0, 0, 1;
    %jmp T_14.12;
T_14.6 ;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x2ec6c40_0, 0, 1;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x2ec6900_0, 0, 1;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x2ec69d0_0, 0, 1;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x2ec6b70_0, 0, 1;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x2ec6aa0_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec65b0_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec6200_0, 0, 1;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x2ec62f0_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec64c0_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec63f0_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec6720_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec6d10_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec6120_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec6680_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec67c0_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec6860_0, 0, 1;
    %jmp T_14.12;
T_14.7 ;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x2ec6c40_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec6900_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec69d0_0, 0, 1;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x2ec6b70_0, 0, 1;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x2ec6aa0_0, 0, 1;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x2ec65b0_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec6200_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec62f0_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec64c0_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec63f0_0, 0, 1;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x2ec6720_0, 0, 1;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x2ec6d10_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec6120_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec6680_0, 0, 1;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x2ec67c0_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec6860_0, 0, 1;
    %jmp T_14.12;
T_14.8 ;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x2ec6c40_0, 0, 1;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x2ec6900_0, 0, 1;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x2ec69d0_0, 0, 1;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x2ec6b70_0, 0, 1;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x2ec6aa0_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec65b0_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec6200_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec62f0_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec64c0_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec63f0_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec6720_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec6d10_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec6120_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec6680_0, 0, 1;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x2ec67c0_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec6860_0, 0, 1;
    %jmp T_14.12;
T_14.9 ;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x2ec6c40_0, 0, 1;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x2ec6900_0, 0, 1;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x2ec69d0_0, 0, 1;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x2ec6b70_0, 0, 1;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x2ec6aa0_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec65b0_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec6200_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec62f0_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec64c0_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec63f0_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec6720_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec6d10_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec6120_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec6680_0, 0, 1;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x2ec67c0_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec6860_0, 0, 1;
    %jmp T_14.12;
T_14.10 ;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x2ec6c40_0, 0, 1;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x2ec6900_0, 0, 1;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x2ec69d0_0, 0, 1;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x2ec6b70_0, 0, 1;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x2ec6aa0_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec65b0_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec6200_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec62f0_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec64c0_0, 0, 1;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x2ec63f0_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec6720_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec6d10_0, 0, 1;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x2ec6120_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec6680_0, 0, 1;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x2ec67c0_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ec6860_0, 0, 1;
    %jmp T_14.12;
T_14.12 ;
    %pop/vec4 1;
    %jmp T_14;
    .thread T_14, $push;
    .scope S_0x2e950f0;
T_15 ;
    %wait E_0x2e44430;
    %load/vec4 v0x2ecab90_0;
    %nor/r;
    %flag_set/vec4 8;
    %jmp/0xz  T_15.0, 8;
    %pushi/vec4 0, 0, 5;
    %assign/vec4 v0x2eca600_0, 0;
    %pushi/vec4 0, 0, 1;
    %assign/vec4 v0x2eca560_0, 0;
    %jmp T_15.1;
T_15.0 ;
    %load/vec4 v0x2eca600_0;
    %pad/u 32;
    %cmpi/e 2, 0, 32;
    %jmp/0xz  T_15.2, 4;
    %load/vec4 v0x2eca560_0;
    %inv;
    %assign/vec4 v0x2eca560_0, 0;
    %pushi/vec4 0, 0, 5;
    %assign/vec4 v0x2eca600_0, 0;
    %jmp T_15.3;
T_15.2 ;
    %load/vec4 v0x2eca600_0;
    %addi 1, 0, 5;
    %assign/vec4 v0x2eca600_0, 0;
T_15.3 ;
T_15.1 ;
    %jmp T_15;
    .thread T_15;
    .scope S_0x2e7f070;
T_16 ;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ecc580_0, 0, 1;
T_16.0 ;
    %delay 10000, 0;
    %load/vec4 v0x2ecc580_0;
    %inv;
    %store/vec4 v0x2ecc580_0, 0, 1;
    %jmp T_16.0;
T_16.1 ;
    %end;
    .thread T_16;
    .scope S_0x2e7f070;
T_17 ;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ecc6c0_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2ecc620_0, 0, 1;
    %delay 100000, 0;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x2ecc6c0_0, 0, 1;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x2ecc620_0, 0, 1;
    %end;
    .thread T_17;
    .scope S_0x2e7f070;
T_18 ;
    %vpi_call 2 59 "$dumpfile", "tb_led_panel_video.vcd" {0 0 0};
    %vpi_call 2 60 "$dumpvars", 32'sb00000000000000000000000000000000, S_0x2e7f070 {0 0 0};
    %delay 1215752192, 23;
    %vpi_call 2 64 "$finish" {0 0 0};
    %end;
    .thread T_18;
# The file index is used to find the file name in the following table.
:file_names 11;
    "N/A";
    "<interactive>";
    "tb_led_panel_video.v";
    "Led_panel_video.v";
    "Comparador.v";
    "Contador.v";
    "Multiplexor.v";
    "Control_video.v";
    "Lsr_led.v";
    "memory_doble.v";
    "memory_principal.v";
# EOF
