/* Generated by Yosys 0.57+263 (git sha1 da2e021e3, g++ 14.2.0-19ubuntu2 -fPIC -O3) */

(* top =  1  *)
(* src = "bin2bcd.v:1.1-46.10" *)
module bin2bcd(clk, rst, init, A, result, done);
  (* src = "bin2bcd.v:4.17-4.20" *)
  input clk;
  wire clk;
  (* src = "bin2bcd.v:3.17-3.20" *)
  input rst;
  wire rst;
  (* src = "bin2bcd.v:5.17-5.21" *)
  input init;
  wire init;
  (* src = "bin2bcd.v:6.17-6.18" *)
  input [15:0] A;
  wire [15:0] A;
  (* src = "bin2bcd.v:7.17-7.23" *)
  output [19:0] result;
  wire [19:0] result;
  (* src = "bin2bcd.v:8.17-8.21" *)
  output done;
  wire done;
  (* hdlname = "comp0 in_A" *)
  (* src = "add_sub_c2.v:3.15-3.19" *)
  wire [3:0] \comp0.in_A ;
  (* hdlname = "comp0 in_B" *)
  (* src = "add_sub_c2.v:4.15-4.19" *)
  wire [3:0] \comp0.in_B ;
  (* hdlname = "comp1 in_A" *)
  (* src = "add_sub_c2.v:3.15-3.19" *)
  wire [3:0] \comp1.in_A ;
  (* hdlname = "comp1 in_B" *)
  (* src = "add_sub_c2.v:4.15-4.19" *)
  wire [3:0] \comp1.in_B ;
  (* hdlname = "comp2 in_A" *)
  (* src = "add_sub_c2.v:3.15-3.19" *)
  wire [3:0] \comp2.in_A ;
  (* hdlname = "comp2 in_B" *)
  (* src = "add_sub_c2.v:4.15-4.19" *)
  wire [3:0] \comp2.in_B ;
  (* hdlname = "comp3 in_A" *)
  (* src = "add_sub_c2.v:3.15-3.19" *)
  wire [3:0] \comp3.in_A ;
  (* hdlname = "comp3 in_B" *)
  (* src = "add_sub_c2.v:4.15-4.19" *)
  wire [3:0] \comp3.in_B ;
  (* hdlname = "comp4 in_A" *)
  (* src = "add_sub_c2.v:3.15-3.19" *)
  wire [3:0] \comp4.in_A ;
  (* hdlname = "comp4 in_B" *)
  (* src = "add_sub_c2.v:4.15-4.19" *)
  wire [3:0] \comp4.in_B ;
  (* hdlname = "control0 add" *)
  (* src = "ctrl_b2b.v:17.13-17.16" *)
  wire \control0.add ;
  (* hdlname = "control0 clk" *)
  (* src = "ctrl_b2b.v:7.14-7.17" *)
  wire \control0.clk ;
  (* hdlname = "control0 count" *)
  (* src = "ctrl_b2b.v:29.12-29.17" *)
  wire [3:0] \control0.count ;
  wire \control0.count_SB_DFFESR_Q_3_D ;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [3:0] \control0.count_SB_DFFESR_Q_D ;
  (* abc9_carry = 32'd1 *)
  (* src = "ctrl_b2b.v:68.15-68.24|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/usr/local/bin/../share/yosys/ice40/abc9_model.v:4.9-4.11" *)
  wire \control0.count_SB_DFFESR_Q_D_SB_LUT4_O_2_I3 ;
  (* abc9_carry = 32'd1 *)
  (* src = "ctrl_b2b.v:68.15-68.24|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/usr/local/bin/../share/yosys/ice40/abc9_model.v:4.9-4.11" *)
  wire \control0.count_SB_DFFESR_Q_D_SB_LUT4_O_I3 ;
  (* hdlname = "control0 done" *)
  (* src = "ctrl_b2b.v:18.13-18.17" *)
  wire \control0.done ;
  (* hdlname = "control0 init" *)
  (* src = "ctrl_b2b.v:9.14-9.18" *)
  wire \control0.init ;
  (* hdlname = "control0 ld" *)
  (* src = "ctrl_b2b.v:14.13-14.15" *)
  wire \control0.ld ;
  (* hdlname = "control0 ld_msb" *)
  (* src = "ctrl_b2b.v:16.13-16.19" *)
  wire \control0.ld_msb ;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [3:0] \control0.ld_msb_SB_LUT4_O_I2 ;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [3:0] \control0.ld_msb_SB_LUT4_O_I2_SB_LUT4_I3_O ;
  (* hdlname = "control0 rst" *)
  (* src = "ctrl_b2b.v:8.14-8.17" *)
  wire \control0.rst ;
  (* hdlname = "control0 sel" *)
  (* src = "ctrl_b2b.v:15.13-15.16" *)
  wire \control0.sel ;
  (* hdlname = "control0 sh" *)
  (* src = "ctrl_b2b.v:13.13-13.15" *)
  wire \control0.sh ;
  (* onehot = 32'd1 *)
  wire [5:0] \control0.state ;
  wire \control0.state_SB_DFF_Q_1_D ;
  wire \control0.state_SB_DFF_Q_2_D ;
  wire \control0.state_SB_DFF_Q_3_D ;
  wire \control0.state_SB_DFF_Q_4_D ;
  wire \control0.state_SB_DFF_Q_5_D ;
  wire \control0.state_SB_DFF_Q_D ;
  (* hdlname = "control0 z" *)
  (* src = "ctrl_b2b.v:10.14-10.15" *)
  wire \control0.z ;
  (* hdlname = "count0 clk" *)
  (* src = "count.v:3.9-3.12" *)
  wire \count0.clk ;
  (* hdlname = "count0 cont" *)
  (* src = "count.v:8.13-8.17" *)
  (* unused_bits = "3" *)
  wire [4:0] \count0.cont ;
  wire \count0.cont_SB_DFFNESR_Q_1_D ;
  wire \count0.cont_SB_DFFNESR_Q_2_D ;
  wire \count0.cont_SB_DFFNESR_Q_D ;
  (* abc9_carry = 32'd1 *)
  (* src = "count.v:16.16-16.22|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/usr/local/bin/../share/yosys/ice40/abc9_model.v:4.9-4.11" *)
  wire \count0.cont_SB_DFFNESR_Q_D_SB_LUT4_O_I3 ;
  wire \count0.cont_SB_DFFNESS_Q_D ;
  (* abc9_carry = 32'd1 *)
  (* src = "count.v:16.16-16.22|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/usr/local/bin/../share/yosys/ice40/abc9_model.v:4.9-4.11" *)
  wire \count0.cont_SB_DFFNESS_Q_D_SB_LUT4_O_I3 ;
  (* abc9_carry = 32'd1 *)
  (* src = "count.v:16.16-16.22|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/usr/local/bin/../share/yosys/ice40/abc9_model.v:4.9-4.11" *)
  wire \count0.cont_SB_DFFNESS_Q_D_SB_LUT4_O_I3_SB_CARRY_CO_CI ;
  (* force_downto = 32'd1 *)
  (* src = "count.v:16.16-16.22|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/usr/local/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [3:0] \count0.cont_SB_DFFNESS_Q_D_SB_LUT4_O_I3_SB_CARRY_CO_I0 ;
  (* hdlname = "count0 dec" *)
  (* src = "count.v:5.9-5.12" *)
  wire \count0.dec ;
  (* hdlname = "count0 ld" *)
  (* src = "count.v:4.9-4.11" *)
  wire \count0.ld ;
  (* hdlname = "count0 z" *)
  (* src = "count.v:6.14-6.15" *)
  wire \count0.z ;
  wire \count0.z_SB_DFFN_Q_D ;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [0:0] \count0.z_SB_DFFN_Q_D_SB_LUT4_O_I1 ;
  wire \count0.z_SB_DFFN_Q_D_SB_LUT4_O_I1_SB_DFFNESS_Q_D ;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] \count0.z_SB_DFFN_Q_D_SB_LUT4_O_I3 ;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] \count0.z_SB_LUT4_I2_O ;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [3:0] init_SB_LUT4_I0_I2;
  (* hdlname = "lsr40 clk" *)
  (* src = "lsr4.v:3.18-3.21" *)
  wire \lsr40.clk ;
  (* hdlname = "lsr40 data" *)
  (* src = "lsr4.v:11.16-11.20" *)
  wire [35:0] \lsr40.data ;
  wire \lsr40.data_SB_DFFNESR_Q_10_D ;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] \lsr40.data_SB_DFFNESR_Q_10_D_SB_LUT4_O_I3 ;
  wire \lsr40.data_SB_DFFNESR_Q_11_D ;
  wire \lsr40.data_SB_DFFNESR_Q_12_D ;
  wire \lsr40.data_SB_DFFNESR_Q_13_D ;
  wire \lsr40.data_SB_DFFNESR_Q_14_D ;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] \lsr40.data_SB_DFFNESR_Q_14_D_SB_LUT4_O_I3 ;
  wire \lsr40.data_SB_DFFNESR_Q_15_D ;
  wire \lsr40.data_SB_DFFNESR_Q_16_D ;
  wire \lsr40.data_SB_DFFNESR_Q_16_E ;
  wire \lsr40.data_SB_DFFNESR_Q_17_D ;
  wire \lsr40.data_SB_DFFNESR_Q_18_D ;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] \lsr40.data_SB_DFFNESR_Q_18_D_SB_LUT4_O_I3 ;
  wire \lsr40.data_SB_DFFNESR_Q_19_D ;
  wire \lsr40.data_SB_DFFNESR_Q_1_D ;
  wire \lsr40.data_SB_DFFNESR_Q_20_D ;
  wire \lsr40.data_SB_DFFNESR_Q_20_E ;
  wire \lsr40.data_SB_DFFNESR_Q_2_D ;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] \lsr40.data_SB_DFFNESR_Q_2_D_SB_LUT4_O_I3 ;
  (* abc9_carry = 32'd1 *)
  (* src = "add_sub_c2.v:8.12-8.23|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/usr/local/bin/../share/yosys/ice40/abc9_model.v:4.9-4.11" *)
  wire \lsr40.data_SB_DFFNESR_Q_2_D_SB_LUT4_O_I3_SB_LUT4_O_I3 ;
  wire \lsr40.data_SB_DFFNESR_Q_3_D ;
  wire \lsr40.data_SB_DFFNESR_Q_4_D ;
  wire \lsr40.data_SB_DFFNESR_Q_4_E ;
  wire \lsr40.data_SB_DFFNESR_Q_5_D ;
  wire \lsr40.data_SB_DFFNESR_Q_6_D ;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] \lsr40.data_SB_DFFNESR_Q_6_D_SB_LUT4_O_I3 ;
  (* abc9_carry = 32'd1 *)
  (* src = "add_sub_c2.v:8.12-8.23|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/usr/local/bin/../share/yosys/ice40/abc9_model.v:4.9-4.11" *)
  wire \lsr40.data_SB_DFFNESR_Q_6_D_SB_LUT4_O_I3_SB_LUT4_O_I3 ;
  wire \lsr40.data_SB_DFFNESR_Q_7_D ;
  wire \lsr40.data_SB_DFFNESR_Q_8_D ;
  wire \lsr40.data_SB_DFFNESR_Q_8_E ;
  wire \lsr40.data_SB_DFFNESR_Q_9_D ;
  wire \lsr40.data_SB_DFFNESR_Q_9_E ;
  wire \lsr40.data_SB_DFFNESR_Q_R ;
  wire \lsr40.data_SB_DFFNE_Q_10_D ;
  wire \lsr40.data_SB_DFFNE_Q_11_D ;
  wire \lsr40.data_SB_DFFNE_Q_12_D ;
  wire \lsr40.data_SB_DFFNE_Q_13_D ;
  wire \lsr40.data_SB_DFFNE_Q_14_D ;
  wire \lsr40.data_SB_DFFNE_Q_1_D ;
  wire \lsr40.data_SB_DFFNE_Q_2_D ;
  wire \lsr40.data_SB_DFFNE_Q_3_D ;
  wire \lsr40.data_SB_DFFNE_Q_4_D ;
  wire \lsr40.data_SB_DFFNE_Q_5_D ;
  wire \lsr40.data_SB_DFFNE_Q_6_D ;
  wire \lsr40.data_SB_DFFNE_Q_7_D ;
  wire \lsr40.data_SB_DFFNE_Q_8_D ;
  wire \lsr40.data_SB_DFFNE_Q_9_D ;
  wire \lsr40.data_SB_DFFNE_Q_D ;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] \lsr40.data_SB_DFFNE_Q_E ;
  (* hdlname = "lsr40 in_R1" *)
  (* src = "lsr4.v:7.18-7.23" *)
  wire [15:0] \lsr40.in_R1 ;
  (* hdlname = "lsr40 out_R" *)
  (* src = "lsr4.v:9.18-9.23" *)
  wire [19:0] \lsr40.out_R ;
  (* hdlname = "lsr40 rst_ld" *)
  (* src = "lsr4.v:4.18-4.24" *)
  wire \lsr40.rst_ld ;
  (* hdlname = "lsr40 shift" *)
  (* src = "lsr4.v:5.18-5.23" *)
  wire \lsr40.shift ;
  (* hdlname = "mux0 in1" *)
  (* src = "mux2.v:3.20-3.23" *)
  wire [3:0] \mux0.in1 ;
  (* hdlname = "mux0 in2" *)
  (* src = "mux2.v:4.20-4.23" *)
  wire [3:0] \mux0.in2 ;
  (* hdlname = "mux0 out" *)
  (* src = "mux2.v:6.20-6.23" *)
  wire [3:0] \mux0.out ;
  (* hdlname = "mux0 sel" *)
  (* src = "mux2.v:5.20-5.23" *)
  wire \mux0.sel ;
  (* hdlname = "mux1 in1" *)
  (* src = "mux2.v:3.20-3.23" *)
  wire [3:0] \mux1.in1 ;
  (* hdlname = "mux1 in2" *)
  (* src = "mux2.v:4.20-4.23" *)
  wire [3:0] \mux1.in2 ;
  (* hdlname = "mux1 out" *)
  (* src = "mux2.v:6.20-6.23" *)
  wire [3:0] \mux1.out ;
  (* hdlname = "mux1 sel" *)
  (* src = "mux2.v:5.20-5.23" *)
  wire \mux1.sel ;
  (* hdlname = "mux2 in1" *)
  (* src = "mux2.v:3.20-3.23" *)
  wire [3:0] \mux2.in1 ;
  (* hdlname = "mux2 in2" *)
  (* src = "mux2.v:4.20-4.23" *)
  wire [3:0] \mux2.in2 ;
  (* hdlname = "mux2 out" *)
  (* src = "mux2.v:6.20-6.23" *)
  wire [3:0] \mux2.out ;
  (* hdlname = "mux2 sel" *)
  (* src = "mux2.v:5.20-5.23" *)
  wire \mux2.sel ;
  (* hdlname = "mux3 in1" *)
  (* src = "mux2.v:3.20-3.23" *)
  wire [3:0] \mux3.in1 ;
  (* hdlname = "mux3 in2" *)
  (* src = "mux2.v:4.20-4.23" *)
  wire [3:0] \mux3.in2 ;
  (* hdlname = "mux3 out" *)
  (* src = "mux2.v:6.20-6.23" *)
  wire [3:0] \mux3.out ;
  (* hdlname = "mux3 sel" *)
  (* src = "mux2.v:5.20-5.23" *)
  wire \mux3.sel ;
  (* hdlname = "mux4 in1" *)
  (* src = "mux2.v:3.20-3.23" *)
  wire [3:0] \mux4.in1 ;
  (* hdlname = "mux4 in2" *)
  (* src = "mux2.v:4.20-4.23" *)
  wire [3:0] \mux4.in2 ;
  (* hdlname = "mux4 out" *)
  (* src = "mux2.v:6.20-6.23" *)
  wire [3:0] \mux4.out ;
  (* hdlname = "mux4 sel" *)
  (* src = "mux2.v:5.20-5.23" *)
  wire \mux4.sel ;
  (* hdlname = "reg0 clk" *)
  (* src = "reg_msb.v:3.21-3.24" *)
  wire \reg0.clk ;
  (* hdlname = "reg0 cont" *)
  (* src = "reg_msb.v:10.13-10.17" *)
  wire [4:0] \reg0.cont ;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] \reg0.cont_SB_DFFNESR_Q_1_D ;
  (* abc9_carry = 32'd1 *)
  (* src = "add_sub_c2.v:8.12-8.23|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/usr/local/bin/../share/yosys/ice40/abc9_model.v:4.9-4.11" *)
  wire \reg0.cont_SB_DFFNESR_Q_1_D_SB_LUT4_O_I3 ;
  (* abc9_carry = 32'd1 *)
  (* src = "add_sub_c2.v:8.12-8.23|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/usr/local/bin/../share/yosys/ice40/abc9_model.v:4.9-4.11" *)
  wire \reg0.cont_SB_DFFNESR_Q_1_D_SB_LUT4_O_I3_SB_CARRY_CO_CI ;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] \reg0.cont_SB_DFFNESR_Q_2_D ;
  (* abc9_carry = 32'd1 *)
  (* src = "add_sub_c2.v:8.12-8.23|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/usr/local/bin/../share/yosys/ice40/abc9_model.v:4.9-4.11" *)
  wire \reg0.cont_SB_DFFNESR_Q_2_D_SB_LUT4_O_I3 ;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] \reg0.cont_SB_DFFNESR_Q_3_D ;
  (* abc9_carry = 32'd1 *)
  (* src = "add_sub_c2.v:8.12-8.23|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/usr/local/bin/../share/yosys/ice40/abc9_model.v:4.9-4.11" *)
  wire \reg0.cont_SB_DFFNESR_Q_3_D_SB_LUT4_O_I3 ;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] \reg0.cont_SB_DFFNESR_Q_4_D ;
  (* abc9_carry = 32'd1 *)
  (* src = "add_sub_c2.v:8.12-8.23|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/usr/local/bin/../share/yosys/ice40/abc9_model.v:4.9-4.11" *)
  wire \reg0.cont_SB_DFFNESR_Q_4_D_SB_LUT4_O_I3 ;
  (* abc9_carry = 32'd1 *)
  (* src = "add_sub_c2.v:8.12-8.23|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/usr/local/bin/../share/yosys/ice40/abc9_model.v:4.9-4.11" *)
  wire \reg0.cont_SB_DFFNESR_Q_4_D_SB_LUT4_O_I3_SB_CARRY_CO_CI ;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] \reg0.cont_SB_DFFNESR_Q_D ;
  (* abc9_carry = 32'd1 *)
  (* src = "add_sub_c2.v:8.12-8.23|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/usr/local/bin/../share/yosys/ice40/abc9_model.v:4.9-4.11" *)
  wire \reg0.cont_SB_DFFNESR_Q_D_SB_LUT4_O_I3 ;
  (* abc9_carry = 32'd1 *)
  (* src = "add_sub_c2.v:8.12-8.23|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/usr/local/bin/../share/yosys/ice40/abc9_model.v:4.9-4.11" *)
  wire \reg0.cont_SB_DFFNESR_Q_D_SB_LUT4_O_I3_SB_CARRY_CO_CI ;
  wire \reg0.cont_SB_DFFNESR_Q_E ;
  (* hdlname = "reg0 ld" *)
  (* src = "reg_msb.v:5.21-5.23" *)
  wire \reg0.ld ;
  (* hdlname = "reg0 oe" *)
  (* src = "reg_msb.v:6.21-6.23" *)
  wire \reg0.oe ;
  (* hdlname = "reg0 reset" *)
  (* src = "reg_msb.v:4.21-4.26" *)
  wire \reg0.reset ;
  (* src = "bin2bcd.v:25.15-25.20" *)
  wire [19:0] w_MUX;
  (* src = "bin2bcd.v:14.8-14.13" *)
  wire w_add;
  (* src = "bin2bcd.v:21.14-21.19" *)
  wire [3:0] w_cen;
  (* src = "bin2bcd.v:20.14-20.19" *)
  wire [3:0] w_dec;
  (* src = "bin2bcd.v:23.14-23.19" *)
  wire [3:0] w_dmi;
  (* src = "bin2bcd.v:11.8-11.12" *)
  wire w_ld;
  (* src = "bin2bcd.v:13.8-13.16" *)
  wire w_ld_msb;
  (* src = "bin2bcd.v:12.8-12.13" *)
  wire w_sel;
  (* src = "bin2bcd.v:10.8-10.12" *)
  wire w_sh;
  (* src = "bin2bcd.v:22.14-22.19" *)
  wire [3:0] w_umi;
  (* src = "bin2bcd.v:19.14-19.19" *)
  wire [3:0] w_uni;
  (* src = "bin2bcd.v:15.8-15.11" *)
  wire w_z;
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hff0c)
  ) \control0.add_SB_LUT4_I1  (
    .I0(1'h0),
    .I1(\control0.add ),
    .I2(\reg0.cont [4]),
    .I3(\lsr40.data_SB_DFFNE_Q_E [2]),
    .O(\lsr40.data_SB_DFFNESR_Q_20_E )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hff0c)
  ) \control0.add_SB_LUT4_I1_1  (
    .I0(1'h0),
    .I1(\control0.add ),
    .I2(\reg0.cont [3]),
    .I3(\lsr40.data_SB_DFFNE_Q_E [2]),
    .O(\lsr40.data_SB_DFFNESR_Q_16_E )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hff0c)
  ) \control0.add_SB_LUT4_I1_2  (
    .I0(1'h0),
    .I1(\control0.add ),
    .I2(\reg0.cont [0]),
    .I3(\lsr40.data_SB_DFFNE_Q_E [2]),
    .O(\lsr40.data_SB_DFFNESR_Q_9_E )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hff0c)
  ) \control0.add_SB_LUT4_I1_3  (
    .I0(1'h0),
    .I1(\control0.add ),
    .I2(\reg0.cont [2]),
    .I3(\lsr40.data_SB_DFFNE_Q_E [2]),
    .O(\lsr40.data_SB_DFFNESR_Q_8_E )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hff0c)
  ) \control0.add_SB_LUT4_I1_4  (
    .I0(1'h0),
    .I1(\control0.add ),
    .I2(\reg0.cont [1]),
    .I3(\lsr40.data_SB_DFFNE_Q_E [2]),
    .O(\lsr40.data_SB_DFFNESR_Q_4_E )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hcecc)
  ) \control0.add_SB_LUT4_O  (
    .I0(\control0.add ),
    .I1(\control0.state [1]),
    .I2(\control0.state [0]),
    .I3(\control0.ld_msb_SB_LUT4_O_I2_SB_LUT4_I3_O [3]),
    .O(\control0.add )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "ctrl_b2b.v:31.1-75.4|/usr/local/bin/../share/yosys/ice40/ff_map.v:24.66-24.119" *)
  SB_DFFESR \control0.count_SB_DFFESR_Q  (
    .C(clk),
    .D(\control0.count_SB_DFFESR_Q_D [3]),
    .E(init_SB_LUT4_I0_I2[2]),
    .Q(\control0.count [3]),
    .R(rst)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "ctrl_b2b.v:31.1-75.4|/usr/local/bin/../share/yosys/ice40/ff_map.v:24.66-24.119" *)
  SB_DFFESR \control0.count_SB_DFFESR_Q_1  (
    .C(clk),
    .D(\control0.count_SB_DFFESR_Q_D [2]),
    .E(init_SB_LUT4_I0_I2[2]),
    .Q(\control0.count [2]),
    .R(rst)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "ctrl_b2b.v:31.1-75.4|/usr/local/bin/../share/yosys/ice40/ff_map.v:24.66-24.119" *)
  SB_DFFESR \control0.count_SB_DFFESR_Q_2  (
    .C(clk),
    .D(\control0.count_SB_DFFESR_Q_D [1]),
    .E(init_SB_LUT4_I0_I2[2]),
    .Q(\control0.count [1]),
    .R(rst)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "ctrl_b2b.v:31.1-75.4|/usr/local/bin/../share/yosys/ice40/ff_map.v:24.66-24.119" *)
  SB_DFFESR \control0.count_SB_DFFESR_Q_3  (
    .C(clk),
    .D(\control0.count_SB_DFFESR_Q_3_D ),
    .E(init_SB_LUT4_I0_I2[2]),
    .Q(\control0.count [0]),
    .R(rst)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:12.34-13.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h00ff)
  ) \control0.count_SB_DFFESR_Q_3_D_SB_LUT4_O  (
    .I0(1'h0),
    .I1(1'h0),
    .I2(1'h0),
    .I3(\control0.count [0]),
    .O(\control0.count_SB_DFFESR_Q_3_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "ctrl_b2b.v:68.15-68.24|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/usr/local/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) \control0.count_SB_DFFESR_Q_D_SB_LUT4_O  (
    .I0(1'h0),
    .I1(1'h0),
    .I2(\control0.count [3]),
    .I3(\control0.count_SB_DFFESR_Q_D_SB_LUT4_O_I3 ),
    .O(\control0.count_SB_DFFESR_Q_D [3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "ctrl_b2b.v:68.15-68.24|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/usr/local/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) \control0.count_SB_DFFESR_Q_D_SB_LUT4_O_1  (
    .I0(1'h0),
    .I1(1'h0),
    .I2(\control0.count [1]),
    .I3(\control0.count [0]),
    .O(\control0.count_SB_DFFESR_Q_D [1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "ctrl_b2b.v:68.15-68.24|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/usr/local/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) \control0.count_SB_DFFESR_Q_D_SB_LUT4_O_2  (
    .I0(1'h0),
    .I1(1'h0),
    .I2(\control0.count [2]),
    .I3(\control0.count_SB_DFFESR_Q_D_SB_LUT4_O_2_I3 ),
    .O(\control0.count_SB_DFFESR_Q_D [2])
  );
  (* src = "ctrl_b2b.v:68.15-68.24|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" *)
  SB_CARRY \control0.count_SB_DFFESR_Q_D_SB_LUT4_O_2_I3_SB_CARRY_CO  (
    .CI(\control0.count [0]),
    .CO(\control0.count_SB_DFFESR_Q_D_SB_LUT4_O_2_I3 ),
    .I0(1'h0),
    .I1(\control0.count [1])
  );
  (* src = "ctrl_b2b.v:68.15-68.24|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" *)
  SB_CARRY \control0.count_SB_DFFESR_Q_D_SB_LUT4_O_I3_SB_CARRY_CO  (
    .CI(\control0.count_SB_DFFESR_Q_D_SB_LUT4_O_2_I3 ),
    .CO(\control0.count_SB_DFFESR_Q_D_SB_LUT4_O_I3 ),
    .I0(1'h0),
    .I1(\control0.count [2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hfc00)
  ) \control0.ld_SB_LUT4_O  (
    .I0(1'h0),
    .I1(\control0.ld ),
    .I2(\control0.state [0]),
    .I3(\control0.ld_msb_SB_LUT4_O_I2_SB_LUT4_I3_O [3]),
    .O(\control0.ld )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:17.34-18.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hfff0)
  ) \control0.ld_msb_SB_LUT4_I3  (
    .I0(1'h0),
    .I1(1'h0),
    .I2(\control0.ld ),
    .I3(\control0.ld_msb ),
    .O(\reg0.cont_SB_DFFNESR_Q_E )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h2f0f)
  ) \control0.ld_msb_SB_LUT4_O  (
    .I0(\control0.ld_msb ),
    .I1(\control0.state [0]),
    .I2(\control0.ld_msb_SB_LUT4_O_I2 [3]),
    .I3(\control0.ld_msb_SB_LUT4_O_I2_SB_LUT4_I3_O [3]),
    .O(\control0.ld_msb )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h0100)
  ) \control0.ld_msb_SB_LUT4_O_I2_SB_LUT4_I3  (
    .I0(\control0.state [5]),
    .I1(\control0.state [4]),
    .I2(\control0.state [1]),
    .I3(\control0.ld_msb_SB_LUT4_O_I2 [3]),
    .O(\control0.ld_msb_SB_LUT4_O_I2_SB_LUT4_I3_O [3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:17.34-18.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h000f)
  ) \control0.ld_msb_SB_LUT4_O_I2_SB_LUT4_O  (
    .I0(1'h0),
    .I1(1'h0),
    .I2(\control0.state [3]),
    .I3(\control0.state [2]),
    .O(\control0.ld_msb_SB_LUT4_O_I2 [3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:17.34-18.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hfff0)
  ) \control0.sh_SB_LUT4_I3  (
    .I0(1'h0),
    .I1(1'h0),
    .I2(\control0.ld ),
    .I3(\control0.sh ),
    .O(\lsr40.data_SB_DFFNE_Q_E [2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hcecc)
  ) \control0.sh_SB_LUT4_O  (
    .I0(\control0.sh ),
    .I1(\control0.state [2]),
    .I2(\control0.state [0]),
    .I3(\control0.ld_msb_SB_LUT4_O_I2_SB_LUT4_I3_O [3]),
    .O(\control0.sh )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/ff_map.v:2.51-2.90" *)
  SB_DFF \control0.state_SB_DFF_Q  (
    .C(clk),
    .D(\control0.state_SB_DFF_Q_D ),
    .Q(\control0.state [5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/ff_map.v:2.51-2.90" *)
  SB_DFF \control0.state_SB_DFF_Q_1  (
    .C(clk),
    .D(\control0.state_SB_DFF_Q_1_D ),
    .Q(\control0.state [4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hfcf0)
  ) \control0.state_SB_DFF_Q_1_D_SB_LUT4_O  (
    .I0(1'h0),
    .I1(\control0.state [4]),
    .I2(\count0.z_SB_LUT4_I2_O [1]),
    .I3(init_SB_LUT4_I0_I2[3]),
    .O(\control0.state_SB_DFF_Q_1_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/ff_map.v:2.51-2.90" *)
  SB_DFF \control0.state_SB_DFF_Q_2  (
    .C(clk),
    .D(\control0.state_SB_DFF_Q_2_D ),
    .Q(\control0.state [3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:17.34-18.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h0f00)
  ) \control0.state_SB_DFF_Q_2_D_SB_LUT4_O  (
    .I0(1'h0),
    .I1(1'h0),
    .I2(rst),
    .I3(\control0.state [2]),
    .O(\control0.state_SB_DFF_Q_2_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/ff_map.v:2.51-2.90" *)
  SB_DFF \control0.state_SB_DFF_Q_3  (
    .C(clk),
    .D(\control0.state_SB_DFF_Q_3_D ),
    .Q(\control0.state [2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/ff_map.v:2.51-2.90" *)
  SB_DFF \control0.state_SB_DFF_Q_4  (
    .C(clk),
    .D(\control0.state_SB_DFF_Q_4_D ),
    .Q(\control0.state [1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/ff_map.v:2.51-2.90" *)
  SB_DFF \control0.state_SB_DFF_Q_5  (
    .C(clk),
    .D(\control0.state_SB_DFF_Q_5_D ),
    .Q(\control0.state [0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:17.34-18.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h0f00)
  ) \control0.state_SB_DFF_Q_D_SB_LUT4_O  (
    .I0(1'h0),
    .I1(1'h0),
    .I2(rst),
    .I3(\control0.state [1]),
    .O(\control0.state_SB_DFF_Q_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "count.v:11.1-21.4|/usr/local/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" *)
  SB_DFFNESR \count0.cont_SB_DFFNESR_Q  (
    .C(clk),
    .D(\count0.cont_SB_DFFNESR_Q_D ),
    .E(\lsr40.data_SB_DFFNE_Q_E [2]),
    .Q(\count0.cont [2]),
    .R(\control0.ld )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "count.v:11.1-21.4|/usr/local/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" *)
  SB_DFFNESR \count0.cont_SB_DFFNESR_Q_1  (
    .C(clk),
    .D(\count0.cont_SB_DFFNESR_Q_1_D ),
    .E(\lsr40.data_SB_DFFNE_Q_E [2]),
    .Q(\count0.cont [1]),
    .R(\control0.ld )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "count.v:16.16-16.22|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/usr/local/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) \count0.cont_SB_DFFNESR_Q_1_D_SB_LUT4_O  (
    .I0(1'h0),
    .I1(\count0.cont [1]),
    .I2(1'h1),
    .I3(\count0.cont [0]),
    .O(\count0.cont_SB_DFFNESR_Q_1_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "count.v:11.1-21.4|/usr/local/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" *)
  SB_DFFNESR \count0.cont_SB_DFFNESR_Q_2  (
    .C(clk),
    .D(\count0.cont_SB_DFFNESR_Q_2_D ),
    .E(\lsr40.data_SB_DFFNE_Q_E [2]),
    .Q(\count0.cont [0]),
    .R(\control0.ld )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:12.34-13.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h00ff)
  ) \count0.cont_SB_DFFNESR_Q_2_D_SB_LUT4_O  (
    .I0(1'h0),
    .I1(1'h0),
    .I2(1'h0),
    .I3(\count0.cont [0]),
    .O(\count0.cont_SB_DFFNESR_Q_2_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "count.v:16.16-16.22|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/usr/local/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) \count0.cont_SB_DFFNESR_Q_D_SB_LUT4_O  (
    .I0(1'h0),
    .I1(\count0.cont [2]),
    .I2(1'h1),
    .I3(\count0.cont_SB_DFFNESR_Q_D_SB_LUT4_O_I3 ),
    .O(\count0.cont_SB_DFFNESR_Q_D )
  );
  (* src = "count.v:16.16-16.22|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" *)
  SB_CARRY \count0.cont_SB_DFFNESR_Q_D_SB_LUT4_O_I3_SB_CARRY_CI  (
    .CI(\count0.cont_SB_DFFNESR_Q_D_SB_LUT4_O_I3 ),
    .CO(\count0.cont_SB_DFFNESS_Q_D_SB_LUT4_O_I3_SB_CARRY_CO_CI ),
    .I0(\count0.cont [2]),
    .I1(1'h1)
  );
  (* src = "count.v:16.16-16.22|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" *)
  SB_CARRY \count0.cont_SB_DFFNESR_Q_D_SB_LUT4_O_I3_SB_CARRY_CO  (
    .CI(\count0.cont [0]),
    .CO(\count0.cont_SB_DFFNESR_Q_D_SB_LUT4_O_I3 ),
    .I0(\count0.cont [1]),
    .I1(1'h1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "count.v:11.1-21.4|/usr/local/bin/../share/yosys/ice40/ff_map.v:23.66-23.119" *)
  SB_DFFNESS \count0.cont_SB_DFFNESS_Q  (
    .C(clk),
    .D(\count0.cont_SB_DFFNESS_Q_D ),
    .E(\lsr40.data_SB_DFFNE_Q_E [2]),
    .Q(\count0.cont [4]),
    .S(\control0.ld )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "count.v:16.16-16.22|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/usr/local/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) \count0.cont_SB_DFFNESS_Q_D_SB_LUT4_O  (
    .I0(1'h0),
    .I1(\count0.cont [4]),
    .I2(1'h1),
    .I3(\count0.cont_SB_DFFNESS_Q_D_SB_LUT4_O_I3 ),
    .O(\count0.cont_SB_DFFNESS_Q_D )
  );
  (* src = "count.v:16.16-16.22|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" *)
  SB_CARRY \count0.cont_SB_DFFNESS_Q_D_SB_LUT4_O_I3_SB_CARRY_CO  (
    .CI(\count0.cont_SB_DFFNESS_Q_D_SB_LUT4_O_I3_SB_CARRY_CO_CI ),
    .CO(\count0.cont_SB_DFFNESS_Q_D_SB_LUT4_O_I3 ),
    .I0(\count0.cont_SB_DFFNESS_Q_D_SB_LUT4_O_I3_SB_CARRY_CO_I0 [1]),
    .I1(1'h1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "count.v:11.1-21.4|/usr/local/bin/../share/yosys/ice40/ff_map.v:1.51-1.90" *)
  SB_DFFN \count0.z_SB_DFFN_Q  (
    .C(clk),
    .D(\count0.z_SB_DFFN_Q_D ),
    .Q(\count0.z )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h0c00)
  ) \count0.z_SB_DFFN_Q_D_SB_LUT4_O  (
    .I0(1'h0),
    .I1(\count0.z_SB_DFFN_Q_D_SB_LUT4_O_I1 ),
    .I2(\count0.cont [0]),
    .I3(\count0.z_SB_DFFN_Q_D_SB_LUT4_O_I3 [2]),
    .O(\count0.z_SB_DFFN_Q_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "count.v:11.1-21.4|/usr/local/bin/../share/yosys/ice40/ff_map.v:23.66-23.119" *)
  SB_DFFNESS \count0.z_SB_DFFN_Q_D_SB_LUT4_O_I1_SB_DFFNESS_Q  (
    .C(clk),
    .D(\count0.z_SB_DFFN_Q_D_SB_LUT4_O_I1_SB_DFFNESS_Q_D ),
    .E(\lsr40.data_SB_DFFNE_Q_E [2]),
    .Q(\count0.z_SB_DFFN_Q_D_SB_LUT4_O_I1 ),
    .S(\control0.ld )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "count.v:16.16-16.22|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/usr/local/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h9669)
  ) \count0.z_SB_DFFN_Q_D_SB_LUT4_O_I1_SB_DFFNESS_Q_D_SB_LUT4_O  (
    .I0(1'h0),
    .I1(\count0.cont_SB_DFFNESS_Q_D_SB_LUT4_O_I3_SB_CARRY_CO_I0 [1]),
    .I2(1'h1),
    .I3(\count0.cont_SB_DFFNESS_Q_D_SB_LUT4_O_I3_SB_CARRY_CO_CI ),
    .O(\count0.z_SB_DFFN_Q_D_SB_LUT4_O_I1_SB_DFFNESS_Q_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:12.34-13.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h00ff)
  ) \count0.z_SB_DFFN_Q_D_SB_LUT4_O_I1_SB_LUT4_I3  (
    .I0(1'h0),
    .I1(1'h0),
    .I2(1'h0),
    .I3(\count0.z_SB_DFFN_Q_D_SB_LUT4_O_I1 ),
    .O(\count0.cont_SB_DFFNESS_Q_D_SB_LUT4_O_I3_SB_CARRY_CO_I0 [1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h0003)
  ) \count0.z_SB_DFFN_Q_D_SB_LUT4_O_I3_SB_LUT4_O  (
    .I0(1'h0),
    .I1(\count0.cont [4]),
    .I2(\count0.cont [2]),
    .I3(\count0.cont [1]),
    .O(\count0.z_SB_DFFN_Q_D_SB_LUT4_O_I3 [2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h3000)
  ) \count0.z_SB_LUT4_I2  (
    .I0(1'h0),
    .I1(rst),
    .I2(\count0.z ),
    .I3(\control0.state [3]),
    .O(\count0.z_SB_LUT4_I2_O [1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h0300)
  ) \count0.z_SB_LUT4_I2_1  (
    .I0(1'h0),
    .I1(rst),
    .I2(\count0.z ),
    .I3(\control0.state [3]),
    .O(\control0.state_SB_DFF_Q_4_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hcecc)
  ) done_SB_LUT4_O (
    .I0(done),
    .I1(\control0.state [4]),
    .I2(\control0.state [0]),
    .I3(\control0.ld_msb_SB_LUT4_O_I2_SB_LUT4_I3_O [3]),
    .O(done)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h44f4)
  ) init_SB_LUT4_I0 (
    .I0(init),
    .I1(\control0.state [0]),
    .I2(init_SB_LUT4_I0_I2[2]),
    .I3(init_SB_LUT4_I0_I2[3]),
    .O(\control0.state_SB_DFF_Q_5_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h3230)
  ) init_SB_LUT4_I0_1 (
    .I0(init),
    .I1(rst),
    .I2(\control0.state [5]),
    .I3(\control0.state [0]),
    .O(\control0.state_SB_DFF_Q_3_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:17.34-18.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hfff0)
  ) init_SB_LUT4_I0_I2_SB_LUT4_O (
    .I0(1'h0),
    .I1(1'h0),
    .I2(rst),
    .I3(\control0.state [4]),
    .O(init_SB_LUT4_I0_I2[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h0155)
  ) init_SB_LUT4_I0_I2_SB_LUT4_O_1 (
    .I0(rst),
    .I1(\control0.count_SB_DFFESR_Q_D [1]),
    .I2(\control0.count_SB_DFFESR_Q_D [2]),
    .I3(\control0.count_SB_DFFESR_Q_D [3]),
    .O(init_SB_LUT4_I0_I2[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "lsr4.v:15.1-36.7|/usr/local/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" *)
  SB_DFFNESR \lsr40.data_SB_DFFNESR_Q  (
    .C(clk),
    .D(A[0]),
    .E(\lsr40.data_SB_DFFNE_Q_E [2]),
    .Q(\lsr40.data [0]),
    .R(\lsr40.data_SB_DFFNESR_Q_R )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "lsr4.v:15.1-36.7|/usr/local/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" *)
  SB_DFFNESR \lsr40.data_SB_DFFNESR_Q_1  (
    .C(clk),
    .D(\lsr40.data_SB_DFFNESR_Q_1_D ),
    .E(\lsr40.data_SB_DFFNESR_Q_4_E ),
    .Q(\lsr40.data [23]),
    .R(\control0.ld )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "lsr4.v:15.1-36.7|/usr/local/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" *)
  SB_DFFNESR \lsr40.data_SB_DFFNESR_Q_10  (
    .C(clk),
    .D(\lsr40.data_SB_DFFNESR_Q_10_D ),
    .E(\lsr40.data_SB_DFFNESR_Q_9_E ),
    .Q(\lsr40.data [18]),
    .R(\control0.ld )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hcfc0)
  ) \lsr40.data_SB_DFFNESR_Q_10_D_SB_LUT4_O  (
    .I0(1'h0),
    .I1(\lsr40.data [17]),
    .I2(\control0.sh ),
    .I3(\lsr40.data_SB_DFFNESR_Q_10_D_SB_LUT4_O_I3 [2]),
    .O(\lsr40.data_SB_DFFNESR_Q_10_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "add_sub_c2.v:8.12-8.23|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/usr/local/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) \lsr40.data_SB_DFFNESR_Q_10_D_SB_LUT4_O_I3_SB_LUT4_O  (
    .I0(1'h0),
    .I1(\lsr40.data [18]),
    .I2(1'h0),
    .I3(\reg0.cont_SB_DFFNESR_Q_4_D_SB_LUT4_O_I3_SB_CARRY_CO_CI ),
    .O(\lsr40.data_SB_DFFNESR_Q_10_D_SB_LUT4_O_I3 [2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "lsr4.v:15.1-36.7|/usr/local/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" *)
  SB_DFFNESR \lsr40.data_SB_DFFNESR_Q_11  (
    .C(clk),
    .D(\lsr40.data_SB_DFFNESR_Q_11_D ),
    .E(\lsr40.data_SB_DFFNESR_Q_9_E ),
    .Q(\lsr40.data [17]),
    .R(\control0.ld )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hfc03)
  ) \lsr40.data_SB_DFFNESR_Q_11_D_SB_LUT4_O  (
    .I0(1'h0),
    .I1(\lsr40.data [17]),
    .I2(\control0.sh ),
    .I3(\lsr40.data [16]),
    .O(\lsr40.data_SB_DFFNESR_Q_11_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "lsr4.v:15.1-36.7|/usr/local/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" *)
  SB_DFFNESR \lsr40.data_SB_DFFNESR_Q_12  (
    .C(clk),
    .D(\lsr40.data_SB_DFFNESR_Q_12_D ),
    .E(\lsr40.data_SB_DFFNESR_Q_9_E ),
    .Q(\lsr40.data [16]),
    .R(\control0.ld )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hcf03)
  ) \lsr40.data_SB_DFFNESR_Q_12_D_SB_LUT4_O  (
    .I0(1'h0),
    .I1(\control0.sh ),
    .I2(\lsr40.data [16]),
    .I3(\lsr40.data [15]),
    .O(\lsr40.data_SB_DFFNESR_Q_12_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "lsr4.v:15.1-36.7|/usr/local/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" *)
  SB_DFFNESR \lsr40.data_SB_DFFNESR_Q_13  (
    .C(clk),
    .D(\lsr40.data_SB_DFFNESR_Q_13_D ),
    .E(\lsr40.data_SB_DFFNESR_Q_16_E ),
    .Q(\lsr40.data [31]),
    .R(\control0.ld )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hcfc0)
  ) \lsr40.data_SB_DFFNESR_Q_13_D_SB_LUT4_O  (
    .I0(1'h0),
    .I1(\lsr40.data [30]),
    .I2(\control0.sh ),
    .I3(\reg0.cont_SB_DFFNESR_Q_1_D [2]),
    .O(\lsr40.data_SB_DFFNESR_Q_13_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "lsr4.v:15.1-36.7|/usr/local/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" *)
  SB_DFFNESR \lsr40.data_SB_DFFNESR_Q_14  (
    .C(clk),
    .D(\lsr40.data_SB_DFFNESR_Q_14_D ),
    .E(\lsr40.data_SB_DFFNESR_Q_16_E ),
    .Q(\lsr40.data [30]),
    .R(\control0.ld )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hcfc0)
  ) \lsr40.data_SB_DFFNESR_Q_14_D_SB_LUT4_O  (
    .I0(1'h0),
    .I1(\lsr40.data [29]),
    .I2(\control0.sh ),
    .I3(\lsr40.data_SB_DFFNESR_Q_14_D_SB_LUT4_O_I3 [2]),
    .O(\lsr40.data_SB_DFFNESR_Q_14_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "add_sub_c2.v:8.12-8.23|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/usr/local/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) \lsr40.data_SB_DFFNESR_Q_14_D_SB_LUT4_O_I3_SB_LUT4_O  (
    .I0(1'h0),
    .I1(\lsr40.data [30]),
    .I2(1'h0),
    .I3(\reg0.cont_SB_DFFNESR_Q_1_D_SB_LUT4_O_I3_SB_CARRY_CO_CI ),
    .O(\lsr40.data_SB_DFFNESR_Q_14_D_SB_LUT4_O_I3 [2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "lsr4.v:15.1-36.7|/usr/local/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" *)
  SB_DFFNESR \lsr40.data_SB_DFFNESR_Q_15  (
    .C(clk),
    .D(\lsr40.data_SB_DFFNESR_Q_15_D ),
    .E(\lsr40.data_SB_DFFNESR_Q_16_E ),
    .Q(\lsr40.data [29]),
    .R(\control0.ld )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf0c3)
  ) \lsr40.data_SB_DFFNESR_Q_15_D_SB_LUT4_O  (
    .I0(1'h0),
    .I1(\lsr40.data [29]),
    .I2(\lsr40.data [28]),
    .I3(\control0.sh ),
    .O(\lsr40.data_SB_DFFNESR_Q_15_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "lsr4.v:15.1-36.7|/usr/local/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" *)
  SB_DFFNESR \lsr40.data_SB_DFFNESR_Q_16  (
    .C(clk),
    .D(\lsr40.data_SB_DFFNESR_Q_16_D ),
    .E(\lsr40.data_SB_DFFNESR_Q_16_E ),
    .Q(\lsr40.data [28]),
    .R(\control0.ld )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hcc0f)
  ) \lsr40.data_SB_DFFNESR_Q_16_D_SB_LUT4_O  (
    .I0(1'h0),
    .I1(\lsr40.data [27]),
    .I2(\lsr40.data [28]),
    .I3(\control0.sh ),
    .O(\lsr40.data_SB_DFFNESR_Q_16_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "lsr4.v:15.1-36.7|/usr/local/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" *)
  SB_DFFNESR \lsr40.data_SB_DFFNESR_Q_17  (
    .C(clk),
    .D(\lsr40.data_SB_DFFNESR_Q_17_D ),
    .E(\lsr40.data_SB_DFFNESR_Q_20_E ),
    .Q(\lsr40.data [35]),
    .R(\control0.ld )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hcfc0)
  ) \lsr40.data_SB_DFFNESR_Q_17_D_SB_LUT4_O  (
    .I0(1'h0),
    .I1(\lsr40.data [34]),
    .I2(\control0.sh ),
    .I3(\reg0.cont_SB_DFFNESR_Q_D [2]),
    .O(\lsr40.data_SB_DFFNESR_Q_17_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "lsr4.v:15.1-36.7|/usr/local/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" *)
  SB_DFFNESR \lsr40.data_SB_DFFNESR_Q_18  (
    .C(clk),
    .D(\lsr40.data_SB_DFFNESR_Q_18_D ),
    .E(\lsr40.data_SB_DFFNESR_Q_20_E ),
    .Q(\lsr40.data [34]),
    .R(\control0.ld )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hcfc0)
  ) \lsr40.data_SB_DFFNESR_Q_18_D_SB_LUT4_O  (
    .I0(1'h0),
    .I1(\lsr40.data [33]),
    .I2(\control0.sh ),
    .I3(\lsr40.data_SB_DFFNESR_Q_18_D_SB_LUT4_O_I3 [2]),
    .O(\lsr40.data_SB_DFFNESR_Q_18_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "add_sub_c2.v:8.12-8.23|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/usr/local/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) \lsr40.data_SB_DFFNESR_Q_18_D_SB_LUT4_O_I3_SB_LUT4_O  (
    .I0(1'h0),
    .I1(\lsr40.data [34]),
    .I2(1'h0),
    .I3(\reg0.cont_SB_DFFNESR_Q_D_SB_LUT4_O_I3_SB_CARRY_CO_CI ),
    .O(\lsr40.data_SB_DFFNESR_Q_18_D_SB_LUT4_O_I3 [2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "lsr4.v:15.1-36.7|/usr/local/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" *)
  SB_DFFNESR \lsr40.data_SB_DFFNESR_Q_19  (
    .C(clk),
    .D(\lsr40.data_SB_DFFNESR_Q_19_D ),
    .E(\lsr40.data_SB_DFFNESR_Q_20_E ),
    .Q(\lsr40.data [33]),
    .R(\control0.ld )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hfc03)
  ) \lsr40.data_SB_DFFNESR_Q_19_D_SB_LUT4_O  (
    .I0(1'h0),
    .I1(\lsr40.data [33]),
    .I2(\control0.sh ),
    .I3(\lsr40.data [32]),
    .O(\lsr40.data_SB_DFFNESR_Q_19_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hcfc0)
  ) \lsr40.data_SB_DFFNESR_Q_1_D_SB_LUT4_O  (
    .I0(1'h0),
    .I1(\lsr40.data [22]),
    .I2(\control0.sh ),
    .I3(\reg0.cont_SB_DFFNESR_Q_3_D [2]),
    .O(\lsr40.data_SB_DFFNESR_Q_1_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "lsr4.v:15.1-36.7|/usr/local/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" *)
  SB_DFFNESR \lsr40.data_SB_DFFNESR_Q_2  (
    .C(clk),
    .D(\lsr40.data_SB_DFFNESR_Q_2_D ),
    .E(\lsr40.data_SB_DFFNESR_Q_4_E ),
    .Q(\lsr40.data [22]),
    .R(\control0.ld )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "lsr4.v:15.1-36.7|/usr/local/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" *)
  SB_DFFNESR \lsr40.data_SB_DFFNESR_Q_20  (
    .C(clk),
    .D(\lsr40.data_SB_DFFNESR_Q_20_D ),
    .E(\lsr40.data_SB_DFFNESR_Q_20_E ),
    .Q(\lsr40.data [32]),
    .R(\control0.ld )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hc0cf)
  ) \lsr40.data_SB_DFFNESR_Q_20_D_SB_LUT4_O  (
    .I0(1'h0),
    .I1(\lsr40.data [31]),
    .I2(\control0.sh ),
    .I3(\lsr40.data [32]),
    .O(\lsr40.data_SB_DFFNESR_Q_20_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hcfc0)
  ) \lsr40.data_SB_DFFNESR_Q_2_D_SB_LUT4_O  (
    .I0(1'h0),
    .I1(\lsr40.data [21]),
    .I2(\control0.sh ),
    .I3(\lsr40.data_SB_DFFNESR_Q_2_D_SB_LUT4_O_I3 [2]),
    .O(\lsr40.data_SB_DFFNESR_Q_2_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "add_sub_c2.v:8.12-8.23|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/usr/local/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) \lsr40.data_SB_DFFNESR_Q_2_D_SB_LUT4_O_I3_SB_LUT4_O  (
    .I0(1'h0),
    .I1(\lsr40.data [22]),
    .I2(1'h0),
    .I3(\lsr40.data_SB_DFFNESR_Q_2_D_SB_LUT4_O_I3_SB_LUT4_O_I3 ),
    .O(\lsr40.data_SB_DFFNESR_Q_2_D_SB_LUT4_O_I3 [2])
  );
  (* src = "add_sub_c2.v:8.12-8.23|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" *)
  SB_CARRY \lsr40.data_SB_DFFNESR_Q_2_D_SB_LUT4_O_I3_SB_LUT4_O_I3_SB_CARRY_CO  (
    .CI(\lsr40.data [20]),
    .CO(\lsr40.data_SB_DFFNESR_Q_2_D_SB_LUT4_O_I3_SB_LUT4_O_I3 ),
    .I0(\lsr40.data [21]),
    .I1(1'h1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "lsr4.v:15.1-36.7|/usr/local/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" *)
  SB_DFFNESR \lsr40.data_SB_DFFNESR_Q_3  (
    .C(clk),
    .D(\lsr40.data_SB_DFFNESR_Q_3_D ),
    .E(\lsr40.data_SB_DFFNESR_Q_4_E ),
    .Q(\lsr40.data [21]),
    .R(\control0.ld )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf0c3)
  ) \lsr40.data_SB_DFFNESR_Q_3_D_SB_LUT4_O  (
    .I0(1'h0),
    .I1(\lsr40.data [21]),
    .I2(\lsr40.data [20]),
    .I3(\control0.sh ),
    .O(\lsr40.data_SB_DFFNESR_Q_3_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "lsr4.v:15.1-36.7|/usr/local/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" *)
  SB_DFFNESR \lsr40.data_SB_DFFNESR_Q_4  (
    .C(clk),
    .D(\lsr40.data_SB_DFFNESR_Q_4_D ),
    .E(\lsr40.data_SB_DFFNESR_Q_4_E ),
    .Q(\lsr40.data [20]),
    .R(\control0.ld )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hcc0f)
  ) \lsr40.data_SB_DFFNESR_Q_4_D_SB_LUT4_O  (
    .I0(1'h0),
    .I1(\lsr40.data [19]),
    .I2(\lsr40.data [20]),
    .I3(\control0.sh ),
    .O(\lsr40.data_SB_DFFNESR_Q_4_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "lsr4.v:15.1-36.7|/usr/local/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" *)
  SB_DFFNESR \lsr40.data_SB_DFFNESR_Q_5  (
    .C(clk),
    .D(\lsr40.data_SB_DFFNESR_Q_5_D ),
    .E(\lsr40.data_SB_DFFNESR_Q_8_E ),
    .Q(\lsr40.data [27]),
    .R(\control0.ld )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hcfc0)
  ) \lsr40.data_SB_DFFNESR_Q_5_D_SB_LUT4_O  (
    .I0(1'h0),
    .I1(\lsr40.data [26]),
    .I2(\control0.sh ),
    .I3(\reg0.cont_SB_DFFNESR_Q_2_D [2]),
    .O(\lsr40.data_SB_DFFNESR_Q_5_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "lsr4.v:15.1-36.7|/usr/local/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" *)
  SB_DFFNESR \lsr40.data_SB_DFFNESR_Q_6  (
    .C(clk),
    .D(\lsr40.data_SB_DFFNESR_Q_6_D ),
    .E(\lsr40.data_SB_DFFNESR_Q_8_E ),
    .Q(\lsr40.data [26]),
    .R(\control0.ld )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hcfc0)
  ) \lsr40.data_SB_DFFNESR_Q_6_D_SB_LUT4_O  (
    .I0(1'h0),
    .I1(\lsr40.data [25]),
    .I2(\control0.sh ),
    .I3(\lsr40.data_SB_DFFNESR_Q_6_D_SB_LUT4_O_I3 [2]),
    .O(\lsr40.data_SB_DFFNESR_Q_6_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "add_sub_c2.v:8.12-8.23|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/usr/local/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) \lsr40.data_SB_DFFNESR_Q_6_D_SB_LUT4_O_I3_SB_LUT4_O  (
    .I0(1'h0),
    .I1(\lsr40.data [26]),
    .I2(1'h0),
    .I3(\lsr40.data_SB_DFFNESR_Q_6_D_SB_LUT4_O_I3_SB_LUT4_O_I3 ),
    .O(\lsr40.data_SB_DFFNESR_Q_6_D_SB_LUT4_O_I3 [2])
  );
  (* src = "add_sub_c2.v:8.12-8.23|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" *)
  SB_CARRY \lsr40.data_SB_DFFNESR_Q_6_D_SB_LUT4_O_I3_SB_LUT4_O_I3_SB_CARRY_CO  (
    .CI(\lsr40.data [24]),
    .CO(\lsr40.data_SB_DFFNESR_Q_6_D_SB_LUT4_O_I3_SB_LUT4_O_I3 ),
    .I0(\lsr40.data [25]),
    .I1(1'h1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "lsr4.v:15.1-36.7|/usr/local/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" *)
  SB_DFFNESR \lsr40.data_SB_DFFNESR_Q_7  (
    .C(clk),
    .D(\lsr40.data_SB_DFFNESR_Q_7_D ),
    .E(\lsr40.data_SB_DFFNESR_Q_8_E ),
    .Q(\lsr40.data [25]),
    .R(\control0.ld )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hfc03)
  ) \lsr40.data_SB_DFFNESR_Q_7_D_SB_LUT4_O  (
    .I0(1'h0),
    .I1(\lsr40.data [25]),
    .I2(\control0.sh ),
    .I3(\lsr40.data [24]),
    .O(\lsr40.data_SB_DFFNESR_Q_7_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "lsr4.v:15.1-36.7|/usr/local/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" *)
  SB_DFFNESR \lsr40.data_SB_DFFNESR_Q_8  (
    .C(clk),
    .D(\lsr40.data_SB_DFFNESR_Q_8_D ),
    .E(\lsr40.data_SB_DFFNESR_Q_8_E ),
    .Q(\lsr40.data [24]),
    .R(\control0.ld )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hc0cf)
  ) \lsr40.data_SB_DFFNESR_Q_8_D_SB_LUT4_O  (
    .I0(1'h0),
    .I1(\lsr40.data [23]),
    .I2(\control0.sh ),
    .I3(\lsr40.data [24]),
    .O(\lsr40.data_SB_DFFNESR_Q_8_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "lsr4.v:15.1-36.7|/usr/local/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" *)
  SB_DFFNESR \lsr40.data_SB_DFFNESR_Q_9  (
    .C(clk),
    .D(\lsr40.data_SB_DFFNESR_Q_9_D ),
    .E(\lsr40.data_SB_DFFNESR_Q_9_E ),
    .Q(\lsr40.data [19]),
    .R(\control0.ld )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hcfc0)
  ) \lsr40.data_SB_DFFNESR_Q_9_D_SB_LUT4_O  (
    .I0(1'h0),
    .I1(\lsr40.data [18]),
    .I2(\control0.sh ),
    .I3(\reg0.cont_SB_DFFNESR_Q_4_D [2]),
    .O(\lsr40.data_SB_DFFNESR_Q_9_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:12.34-13.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h00ff)
  ) \lsr40.data_SB_DFFNESR_Q_R_SB_LUT4_O  (
    .I0(1'h0),
    .I1(1'h0),
    .I2(1'h0),
    .I3(\control0.ld ),
    .O(\lsr40.data_SB_DFFNESR_Q_R )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "lsr4.v:15.1-36.7|/usr/local/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" *)
  SB_DFFNE \lsr40.data_SB_DFFNE_Q  (
    .C(clk),
    .D(\lsr40.data_SB_DFFNE_Q_D ),
    .E(\lsr40.data_SB_DFFNE_Q_E [2]),
    .Q(\lsr40.data [15])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "lsr4.v:15.1-36.7|/usr/local/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" *)
  SB_DFFNE \lsr40.data_SB_DFFNE_Q_1  (
    .C(clk),
    .D(\lsr40.data_SB_DFFNE_Q_1_D ),
    .E(\lsr40.data_SB_DFFNE_Q_E [2]),
    .Q(\lsr40.data [14])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "lsr4.v:15.1-36.7|/usr/local/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" *)
  SB_DFFNE \lsr40.data_SB_DFFNE_Q_10  (
    .C(clk),
    .D(\lsr40.data_SB_DFFNE_Q_10_D ),
    .E(\lsr40.data_SB_DFFNE_Q_E [2]),
    .Q(\lsr40.data [5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hcfc0)
  ) \lsr40.data_SB_DFFNE_Q_10_D_SB_LUT4_O  (
    .I0(1'h0),
    .I1(A[5]),
    .I2(\control0.ld ),
    .I3(\lsr40.data [4]),
    .O(\lsr40.data_SB_DFFNE_Q_10_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "lsr4.v:15.1-36.7|/usr/local/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" *)
  SB_DFFNE \lsr40.data_SB_DFFNE_Q_11  (
    .C(clk),
    .D(\lsr40.data_SB_DFFNE_Q_11_D ),
    .E(\lsr40.data_SB_DFFNE_Q_E [2]),
    .Q(\lsr40.data [4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hcfc0)
  ) \lsr40.data_SB_DFFNE_Q_11_D_SB_LUT4_O  (
    .I0(1'h0),
    .I1(A[4]),
    .I2(\control0.ld ),
    .I3(\lsr40.data [3]),
    .O(\lsr40.data_SB_DFFNE_Q_11_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "lsr4.v:15.1-36.7|/usr/local/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" *)
  SB_DFFNE \lsr40.data_SB_DFFNE_Q_12  (
    .C(clk),
    .D(\lsr40.data_SB_DFFNE_Q_12_D ),
    .E(\lsr40.data_SB_DFFNE_Q_E [2]),
    .Q(\lsr40.data [3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hcfc0)
  ) \lsr40.data_SB_DFFNE_Q_12_D_SB_LUT4_O  (
    .I0(1'h0),
    .I1(A[3]),
    .I2(\control0.ld ),
    .I3(\lsr40.data [2]),
    .O(\lsr40.data_SB_DFFNE_Q_12_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "lsr4.v:15.1-36.7|/usr/local/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" *)
  SB_DFFNE \lsr40.data_SB_DFFNE_Q_13  (
    .C(clk),
    .D(\lsr40.data_SB_DFFNE_Q_13_D ),
    .E(\lsr40.data_SB_DFFNE_Q_E [2]),
    .Q(\lsr40.data [2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hcfc0)
  ) \lsr40.data_SB_DFFNE_Q_13_D_SB_LUT4_O  (
    .I0(1'h0),
    .I1(A[2]),
    .I2(\control0.ld ),
    .I3(\lsr40.data [1]),
    .O(\lsr40.data_SB_DFFNE_Q_13_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "lsr4.v:15.1-36.7|/usr/local/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" *)
  SB_DFFNE \lsr40.data_SB_DFFNE_Q_14  (
    .C(clk),
    .D(\lsr40.data_SB_DFFNE_Q_14_D ),
    .E(\lsr40.data_SB_DFFNE_Q_E [2]),
    .Q(\lsr40.data [1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hcfc0)
  ) \lsr40.data_SB_DFFNE_Q_14_D_SB_LUT4_O  (
    .I0(1'h0),
    .I1(A[1]),
    .I2(\control0.ld ),
    .I3(\lsr40.data [0]),
    .O(\lsr40.data_SB_DFFNE_Q_14_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hcfc0)
  ) \lsr40.data_SB_DFFNE_Q_1_D_SB_LUT4_O  (
    .I0(1'h0),
    .I1(A[14]),
    .I2(\control0.ld ),
    .I3(\lsr40.data [13]),
    .O(\lsr40.data_SB_DFFNE_Q_1_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "lsr4.v:15.1-36.7|/usr/local/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" *)
  SB_DFFNE \lsr40.data_SB_DFFNE_Q_2  (
    .C(clk),
    .D(\lsr40.data_SB_DFFNE_Q_2_D ),
    .E(\lsr40.data_SB_DFFNE_Q_E [2]),
    .Q(\lsr40.data [13])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hcfc0)
  ) \lsr40.data_SB_DFFNE_Q_2_D_SB_LUT4_O  (
    .I0(1'h0),
    .I1(A[13]),
    .I2(\control0.ld ),
    .I3(\lsr40.data [12]),
    .O(\lsr40.data_SB_DFFNE_Q_2_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "lsr4.v:15.1-36.7|/usr/local/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" *)
  SB_DFFNE \lsr40.data_SB_DFFNE_Q_3  (
    .C(clk),
    .D(\lsr40.data_SB_DFFNE_Q_3_D ),
    .E(\lsr40.data_SB_DFFNE_Q_E [2]),
    .Q(\lsr40.data [12])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hcfc0)
  ) \lsr40.data_SB_DFFNE_Q_3_D_SB_LUT4_O  (
    .I0(1'h0),
    .I1(A[12]),
    .I2(\control0.ld ),
    .I3(\lsr40.data [11]),
    .O(\lsr40.data_SB_DFFNE_Q_3_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "lsr4.v:15.1-36.7|/usr/local/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" *)
  SB_DFFNE \lsr40.data_SB_DFFNE_Q_4  (
    .C(clk),
    .D(\lsr40.data_SB_DFFNE_Q_4_D ),
    .E(\lsr40.data_SB_DFFNE_Q_E [2]),
    .Q(\lsr40.data [11])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hcfc0)
  ) \lsr40.data_SB_DFFNE_Q_4_D_SB_LUT4_O  (
    .I0(1'h0),
    .I1(A[11]),
    .I2(\control0.ld ),
    .I3(\lsr40.data [10]),
    .O(\lsr40.data_SB_DFFNE_Q_4_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "lsr4.v:15.1-36.7|/usr/local/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" *)
  SB_DFFNE \lsr40.data_SB_DFFNE_Q_5  (
    .C(clk),
    .D(\lsr40.data_SB_DFFNE_Q_5_D ),
    .E(\lsr40.data_SB_DFFNE_Q_E [2]),
    .Q(\lsr40.data [10])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hcfc0)
  ) \lsr40.data_SB_DFFNE_Q_5_D_SB_LUT4_O  (
    .I0(1'h0),
    .I1(A[10]),
    .I2(\control0.ld ),
    .I3(\lsr40.data [9]),
    .O(\lsr40.data_SB_DFFNE_Q_5_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "lsr4.v:15.1-36.7|/usr/local/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" *)
  SB_DFFNE \lsr40.data_SB_DFFNE_Q_6  (
    .C(clk),
    .D(\lsr40.data_SB_DFFNE_Q_6_D ),
    .E(\lsr40.data_SB_DFFNE_Q_E [2]),
    .Q(\lsr40.data [9])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hcfc0)
  ) \lsr40.data_SB_DFFNE_Q_6_D_SB_LUT4_O  (
    .I0(1'h0),
    .I1(A[9]),
    .I2(\control0.ld ),
    .I3(\lsr40.data [8]),
    .O(\lsr40.data_SB_DFFNE_Q_6_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "lsr4.v:15.1-36.7|/usr/local/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" *)
  SB_DFFNE \lsr40.data_SB_DFFNE_Q_7  (
    .C(clk),
    .D(\lsr40.data_SB_DFFNE_Q_7_D ),
    .E(\lsr40.data_SB_DFFNE_Q_E [2]),
    .Q(\lsr40.data [8])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hcfc0)
  ) \lsr40.data_SB_DFFNE_Q_7_D_SB_LUT4_O  (
    .I0(1'h0),
    .I1(A[8]),
    .I2(\control0.ld ),
    .I3(\lsr40.data [7]),
    .O(\lsr40.data_SB_DFFNE_Q_7_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "lsr4.v:15.1-36.7|/usr/local/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" *)
  SB_DFFNE \lsr40.data_SB_DFFNE_Q_8  (
    .C(clk),
    .D(\lsr40.data_SB_DFFNE_Q_8_D ),
    .E(\lsr40.data_SB_DFFNE_Q_E [2]),
    .Q(\lsr40.data [7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hcfc0)
  ) \lsr40.data_SB_DFFNE_Q_8_D_SB_LUT4_O  (
    .I0(1'h0),
    .I1(A[7]),
    .I2(\control0.ld ),
    .I3(\lsr40.data [6]),
    .O(\lsr40.data_SB_DFFNE_Q_8_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "lsr4.v:15.1-36.7|/usr/local/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" *)
  SB_DFFNE \lsr40.data_SB_DFFNE_Q_9  (
    .C(clk),
    .D(\lsr40.data_SB_DFFNE_Q_9_D ),
    .E(\lsr40.data_SB_DFFNE_Q_E [2]),
    .Q(\lsr40.data [6])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hcfc0)
  ) \lsr40.data_SB_DFFNE_Q_9_D_SB_LUT4_O  (
    .I0(1'h0),
    .I1(A[6]),
    .I2(\control0.ld ),
    .I3(\lsr40.data [5]),
    .O(\lsr40.data_SB_DFFNE_Q_9_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hcfc0)
  ) \lsr40.data_SB_DFFNE_Q_D_SB_LUT4_O  (
    .I0(1'h0),
    .I1(A[15]),
    .I2(\control0.ld ),
    .I3(\lsr40.data [14]),
    .O(\lsr40.data_SB_DFFNE_Q_D )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "reg_msb.v:22.1-30.4|/usr/local/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" *)
  SB_DFFNESR \reg0.cont_SB_DFFNESR_Q  (
    .C(clk),
    .D(\reg0.cont_SB_DFFNESR_Q_D [2]),
    .E(\reg0.cont_SB_DFFNESR_Q_E ),
    .Q(\reg0.cont [4]),
    .R(\control0.ld )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "reg_msb.v:22.1-30.4|/usr/local/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" *)
  SB_DFFNESR \reg0.cont_SB_DFFNESR_Q_1  (
    .C(clk),
    .D(\reg0.cont_SB_DFFNESR_Q_1_D [2]),
    .E(\reg0.cont_SB_DFFNESR_Q_E ),
    .Q(\reg0.cont [3]),
    .R(\control0.ld )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "add_sub_c2.v:8.12-8.23|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/usr/local/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) \reg0.cont_SB_DFFNESR_Q_1_D_SB_LUT4_O  (
    .I0(1'h0),
    .I1(\lsr40.data [31]),
    .I2(\control0.ld_msb ),
    .I3(\reg0.cont_SB_DFFNESR_Q_1_D_SB_LUT4_O_I3 ),
    .O(\reg0.cont_SB_DFFNESR_Q_1_D [2])
  );
  (* src = "add_sub_c2.v:8.12-8.23|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" *)
  SB_CARRY \reg0.cont_SB_DFFNESR_Q_1_D_SB_LUT4_O_I3_SB_CARRY_CO  (
    .CI(\reg0.cont_SB_DFFNESR_Q_1_D_SB_LUT4_O_I3_SB_CARRY_CO_CI ),
    .CO(\reg0.cont_SB_DFFNESR_Q_1_D_SB_LUT4_O_I3 ),
    .I0(\lsr40.data [30]),
    .I1(1'h0)
  );
  (* src = "add_sub_c2.v:8.12-8.23|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" *)
  SB_CARRY \reg0.cont_SB_DFFNESR_Q_1_D_SB_LUT4_O_I3_SB_CARRY_CO_CI_SB_CARRY_CO  (
    .CI(\lsr40.data [28]),
    .CO(\reg0.cont_SB_DFFNESR_Q_1_D_SB_LUT4_O_I3_SB_CARRY_CO_CI ),
    .I0(\lsr40.data [29]),
    .I1(1'h1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "reg_msb.v:22.1-30.4|/usr/local/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" *)
  SB_DFFNESR \reg0.cont_SB_DFFNESR_Q_2  (
    .C(clk),
    .D(\reg0.cont_SB_DFFNESR_Q_2_D [2]),
    .E(\reg0.cont_SB_DFFNESR_Q_E ),
    .Q(\reg0.cont [2]),
    .R(\control0.ld )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "add_sub_c2.v:8.12-8.23|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/usr/local/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) \reg0.cont_SB_DFFNESR_Q_2_D_SB_LUT4_O  (
    .I0(1'h0),
    .I1(\lsr40.data [27]),
    .I2(\control0.ld_msb ),
    .I3(\reg0.cont_SB_DFFNESR_Q_2_D_SB_LUT4_O_I3 ),
    .O(\reg0.cont_SB_DFFNESR_Q_2_D [2])
  );
  (* src = "add_sub_c2.v:8.12-8.23|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" *)
  SB_CARRY \reg0.cont_SB_DFFNESR_Q_2_D_SB_LUT4_O_I3_SB_CARRY_CO  (
    .CI(\lsr40.data_SB_DFFNESR_Q_6_D_SB_LUT4_O_I3_SB_LUT4_O_I3 ),
    .CO(\reg0.cont_SB_DFFNESR_Q_2_D_SB_LUT4_O_I3 ),
    .I0(\lsr40.data [26]),
    .I1(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "reg_msb.v:22.1-30.4|/usr/local/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" *)
  SB_DFFNESR \reg0.cont_SB_DFFNESR_Q_3  (
    .C(clk),
    .D(\reg0.cont_SB_DFFNESR_Q_3_D [2]),
    .E(\reg0.cont_SB_DFFNESR_Q_E ),
    .Q(\reg0.cont [1]),
    .R(\control0.ld )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "add_sub_c2.v:8.12-8.23|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/usr/local/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) \reg0.cont_SB_DFFNESR_Q_3_D_SB_LUT4_O  (
    .I0(1'h0),
    .I1(\lsr40.data [23]),
    .I2(\control0.ld_msb ),
    .I3(\reg0.cont_SB_DFFNESR_Q_3_D_SB_LUT4_O_I3 ),
    .O(\reg0.cont_SB_DFFNESR_Q_3_D [2])
  );
  (* src = "add_sub_c2.v:8.12-8.23|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" *)
  SB_CARRY \reg0.cont_SB_DFFNESR_Q_3_D_SB_LUT4_O_I3_SB_CARRY_CO  (
    .CI(\lsr40.data_SB_DFFNESR_Q_2_D_SB_LUT4_O_I3_SB_LUT4_O_I3 ),
    .CO(\reg0.cont_SB_DFFNESR_Q_3_D_SB_LUT4_O_I3 ),
    .I0(\lsr40.data [22]),
    .I1(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "reg_msb.v:22.1-30.4|/usr/local/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" *)
  SB_DFFNESR \reg0.cont_SB_DFFNESR_Q_4  (
    .C(clk),
    .D(\reg0.cont_SB_DFFNESR_Q_4_D [2]),
    .E(\reg0.cont_SB_DFFNESR_Q_E ),
    .Q(\reg0.cont [0]),
    .R(\control0.ld )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "add_sub_c2.v:8.12-8.23|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/usr/local/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) \reg0.cont_SB_DFFNESR_Q_4_D_SB_LUT4_O  (
    .I0(1'h0),
    .I1(\lsr40.data [19]),
    .I2(\control0.ld_msb ),
    .I3(\reg0.cont_SB_DFFNESR_Q_4_D_SB_LUT4_O_I3 ),
    .O(\reg0.cont_SB_DFFNESR_Q_4_D [2])
  );
  (* src = "add_sub_c2.v:8.12-8.23|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" *)
  SB_CARRY \reg0.cont_SB_DFFNESR_Q_4_D_SB_LUT4_O_I3_SB_CARRY_CO  (
    .CI(\reg0.cont_SB_DFFNESR_Q_4_D_SB_LUT4_O_I3_SB_CARRY_CO_CI ),
    .CO(\reg0.cont_SB_DFFNESR_Q_4_D_SB_LUT4_O_I3 ),
    .I0(\lsr40.data [18]),
    .I1(1'h0)
  );
  (* src = "add_sub_c2.v:8.12-8.23|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" *)
  SB_CARRY \reg0.cont_SB_DFFNESR_Q_4_D_SB_LUT4_O_I3_SB_CARRY_CO_CI_SB_CARRY_CO  (
    .CI(\lsr40.data [16]),
    .CO(\reg0.cont_SB_DFFNESR_Q_4_D_SB_LUT4_O_I3_SB_CARRY_CO_CI ),
    .I0(\lsr40.data [17]),
    .I1(1'h1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "add_sub_c2.v:8.12-8.23|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/usr/local/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) \reg0.cont_SB_DFFNESR_Q_D_SB_LUT4_O  (
    .I0(1'h0),
    .I1(\lsr40.data [35]),
    .I2(\control0.ld_msb ),
    .I3(\reg0.cont_SB_DFFNESR_Q_D_SB_LUT4_O_I3 ),
    .O(\reg0.cont_SB_DFFNESR_Q_D [2])
  );
  (* src = "add_sub_c2.v:8.12-8.23|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" *)
  SB_CARRY \reg0.cont_SB_DFFNESR_Q_D_SB_LUT4_O_I3_SB_CARRY_CO  (
    .CI(\reg0.cont_SB_DFFNESR_Q_D_SB_LUT4_O_I3_SB_CARRY_CO_CI ),
    .CO(\reg0.cont_SB_DFFNESR_Q_D_SB_LUT4_O_I3 ),
    .I0(\lsr40.data [34]),
    .I1(1'h0)
  );
  (* src = "add_sub_c2.v:8.12-8.23|/usr/local/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" *)
  SB_CARRY \reg0.cont_SB_DFFNESR_Q_D_SB_LUT4_O_I3_SB_CARRY_CO_CI_SB_CARRY_CO  (
    .CI(\lsr40.data [32]),
    .CO(\reg0.cont_SB_DFFNESR_Q_D_SB_LUT4_O_I3_SB_CARRY_CO_CI ),
    .I0(\lsr40.data [33]),
    .I1(1'h1)
  );
  assign { \count0.cont_SB_DFFNESS_Q_D_SB_LUT4_O_I3_SB_CARRY_CO_I0 [3:2], \count0.cont_SB_DFFNESS_Q_D_SB_LUT4_O_I3_SB_CARRY_CO_I0 [0] } = { \count0.cont_SB_DFFNESS_Q_D_SB_LUT4_O_I3_SB_CARRY_CO_CI , 2'h2 };
  assign init_SB_LUT4_I0_I2[1:0] = { \control0.state [0], init };
  assign \reg0.cont_SB_DFFNESR_Q_D [1:0] = { \control0.sh , \lsr40.data [34] };
  assign \reg0.cont_SB_DFFNESR_Q_4_D [1:0] = { \control0.sh , \lsr40.data [18] };
  assign \control0.ld_msb_SB_LUT4_O_I2_SB_LUT4_I3_O [2:0] = { \control0.ld_msb_SB_LUT4_O_I2 [3], \control0.state [0], \control0.ld_msb  };
  assign \lsr40.data_SB_DFFNE_Q_E [1:0] = { \reg0.cont [0], \control0.add  };
  assign \control0.ld_msb_SB_LUT4_O_I2 [2:0] = { \control0.state [1], \control0.state [4], \control0.state [5] };
  assign \count0.z_SB_DFFN_Q_D_SB_LUT4_O_I3 [1:0] = { \count0.cont [0], \count0.z_SB_DFFN_Q_D_SB_LUT4_O_I1  };
  assign \lsr40.data_SB_DFFNESR_Q_6_D_SB_LUT4_O_I3 [1:0] = { \control0.sh , \lsr40.data [25] };
  assign \control0.count_SB_DFFESR_Q_D [0] = rst;
  assign \reg0.cont_SB_DFFNESR_Q_2_D [1:0] = { \control0.sh , \lsr40.data [26] };
  assign \lsr40.data_SB_DFFNESR_Q_10_D_SB_LUT4_O_I3 [1:0] = { \control0.sh , \lsr40.data [17] };
  assign \lsr40.data_SB_DFFNESR_Q_18_D_SB_LUT4_O_I3 [1:0] = { \control0.sh , \lsr40.data [33] };
  assign \lsr40.data_SB_DFFNESR_Q_14_D_SB_LUT4_O_I3 [1:0] = { \control0.sh , \lsr40.data [29] };
  assign \lsr40.data_SB_DFFNESR_Q_2_D_SB_LUT4_O_I3 [1:0] = { \control0.sh , \lsr40.data [21] };
  assign \reg0.cont_SB_DFFNESR_Q_1_D [1:0] = { \control0.sh , \lsr40.data [30] };
  assign \reg0.cont_SB_DFFNESR_Q_3_D [1:0] = { \control0.sh , \lsr40.data [22] };
  assign { \count0.z_SB_LUT4_I2_O [2], \count0.z_SB_LUT4_I2_O [0] } = { init_SB_LUT4_I0_I2[3], \control0.state [4] };
  assign \comp0.in_A  = \lsr40.data [19:16];
  assign \comp0.in_B  = { \control0.ld_msb , 3'h3 };
  assign \comp1.in_A  = \lsr40.data [23:20];
  assign \comp1.in_B  = { \control0.ld_msb , 3'h3 };
  assign \comp2.in_A  = \lsr40.data [27:24];
  assign \comp2.in_B  = { \control0.ld_msb , 3'h3 };
  assign \comp3.in_A  = \lsr40.data [31:28];
  assign \comp3.in_B  = { \control0.ld_msb , 3'h3 };
  assign \comp4.in_A  = \lsr40.data [35:32];
  assign \comp4.in_B  = { \control0.ld_msb , 3'h3 };
  assign \control0.clk  = clk;
  assign \control0.done  = done;
  assign \control0.init  = init;
  assign \control0.rst  = rst;
  assign \control0.sel  = \control0.ld_msb ;
  assign \control0.z  = \count0.z ;
  assign \count0.clk  = clk;
  assign \count0.dec  = \control0.sh ;
  assign \count0.ld  = \control0.ld ;
  assign \lsr40.clk  = clk;
  assign \lsr40.in_R1  = A;
  assign \lsr40.out_R  = \lsr40.data [35:16];
  assign \lsr40.rst_ld  = \control0.ld ;
  assign \lsr40.shift  = \control0.sh ;
  assign \mux0.in1  = 4'h3;
  assign \mux0.in2  = 4'hb;
  assign \mux0.out  = { \control0.ld_msb , 3'h3 };
  assign \mux0.sel  = \control0.ld_msb ;
  assign \mux1.in1  = 4'h3;
  assign \mux1.in2  = 4'hb;
  assign \mux1.out  = { \control0.ld_msb , 3'h3 };
  assign \mux1.sel  = \control0.ld_msb ;
  assign \mux2.in1  = 4'h3;
  assign \mux2.in2  = 4'hb;
  assign \mux2.out  = { \control0.ld_msb , 3'h3 };
  assign \mux2.sel  = \control0.ld_msb ;
  assign \mux3.in1  = 4'h3;
  assign \mux3.in2  = 4'hb;
  assign \mux3.out  = { \control0.ld_msb , 3'h3 };
  assign \mux3.sel  = \control0.ld_msb ;
  assign \mux4.in1  = 4'h3;
  assign \mux4.in2  = 4'hb;
  assign \mux4.out  = { \control0.ld_msb , 3'h3 };
  assign \mux4.sel  = \control0.ld_msb ;
  assign \reg0.clk  = clk;
  assign \reg0.ld  = \control0.ld_msb ;
  assign \reg0.oe  = \control0.add ;
  assign \reg0.reset  = \control0.ld ;
  assign result = \lsr40.data [35:16];
  assign w_MUX = { \control0.ld_msb , 3'h3, \control0.ld_msb , 3'h3, \control0.ld_msb , 3'h3, \control0.ld_msb , 3'h3, \control0.ld_msb , 3'h3 };
  assign w_add = \control0.add ;
  assign w_cen = \lsr40.data [27:24];
  assign w_dec = \lsr40.data [23:20];
  assign w_dmi = \lsr40.data [35:32];
  assign w_ld = \control0.ld ;
  assign w_ld_msb = \control0.ld_msb ;
  assign w_sel = \control0.ld_msb ;
  assign w_sh = \control0.sh ;
  assign w_umi = \lsr40.data [31:28];
  assign w_uni = \lsr40.data [19:16];
  assign w_z = \count0.z ;
endmodule
