#! /usr/bin/env bash
exec /home/juan-diego/miniconda3/envs/digital/bin/vvp -f "$0" "$@" <<'# EOF'
:ivl_version "13.0 (devel)" "(0_8-6859-gf50cc35d2-dirty)";
:ivl_delay_selection "TYPICAL";
:vpi_time_precision - 12;
:vpi_module "/home/juan-diego/miniconda3/envs/digital/lib/ivl/system.vpi";
:vpi_module "/home/juan-diego/miniconda3/envs/digital/lib/ivl/vhdl_sys.vpi";
:vpi_module "/home/juan-diego/miniconda3/envs/digital/lib/ivl/vhdl_textio.vpi";
:vpi_module "/home/juan-diego/miniconda3/envs/digital/lib/ivl/v2005_math.vpi";
:vpi_module "/home/juan-diego/miniconda3/envs/digital/lib/ivl/va_math.vpi";
S_0x214f8670 .scope module, "tb_Periferico_BinarioABCD" "tb_Periferico_BinarioABCD" 2 3;
 .timescale -9 -12;
L_0x214ee280 .functor BUFZ 16, v0x2151dc50_0, C4<0000000000000000>, C4<0000000000000000>, C4<0000000000000000>;
L_0x214abf20 .functor BUFZ 1, v0x2151dac0_0, C4<0>, C4<0>, C4<0>;
L_0x214c85a0 .functor BUFZ 4, L_0x21520220, C4<0000>, C4<0000>, C4<0000>;
L_0x215205b0 .functor BUFZ 4, L_0x215202c0, C4<0000>, C4<0000>, C4<0000>;
L_0x21520680 .functor BUFZ 4, L_0x215203b0, C4<0000>, C4<0000>, C4<0000>;
L_0x21520720 .functor BUFZ 4, L_0x21520450, C4<0000>, C4<0000>, C4<0000>;
L_0x21520800 .functor BUFZ 1, v0x215193d0_0, C4<0>, C4<0>, C4<0>;
v0x2151eb70_0 .net "CENT_int", 3 0, L_0x21520680;  1 drivers
v0x2151ec70_0 .var "CLK", 0 0;
v0x2151ed30_0 .net "DEC_int", 3 0, L_0x215205b0;  1 drivers
v0x2151edd0_0 .net "DONE_int", 0 0, L_0x21520800;  1 drivers
v0x2151ee90_0 .net "INIT_int", 0 0, L_0x214abf20;  1 drivers
v0x2151efa0_0 .net "MIL_int", 3 0, L_0x21520720;  1 drivers
v0x2151f080_0 .net "OpA_int", 15 0, L_0x214ee280;  1 drivers
v0x2151f160_0 .net "UNIT_int", 3 0, L_0x214c85a0;  1 drivers
v0x2151f240_0 .var "addr", 5 0;
v0x2151f300_0 .var "cs", 0 0;
v0x2151f3a0_0 .var "d_in", 15 0;
v0x2151f440_0 .net "d_out", 15 0, v0x2151e210_0;  1 drivers
v0x2151f4e0_0 .var/i "i", 31 0;
v0x2151f580_0 .var "rd", 0 0;
v0x2151f620_0 .var "reset", 0 0;
v0x2151f6c0_0 .var "wr", 0 0;
S_0x214b77e0 .scope task, "read_reg" "read_reg" 2 73, 2 73 0, S_0x214f8670;
 .timescale -9 -12;
v0x214ad210_0 .var "address", 5 0;
E_0x214b3720 .event posedge, v0x214f6630_0;
TD_tb_Periferico_BinarioABCD.read_reg ;
    %wait E_0x214b3720;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x2151f300_0, 0, 1;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x2151f580_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2151f6c0_0, 0, 1;
    %load/vec4 v0x214ad210_0;
    %store/vec4 v0x2151f240_0, 0, 6;
    %wait E_0x214b3720;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2151f300_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2151f580_0, 0, 1;
    %end;
S_0x215183c0 .scope module, "uut" "Periferico_BinarioABCD" 2 24, 3 1 0, S_0x214f8670;
 .timescale 0 0;
    .port_info 0 /INPUT 1 "CLK";
    .port_info 1 /INPUT 1 "reset";
    .port_info 2 /INPUT 16 "d_in";
    .port_info 3 /INPUT 1 "cs";
    .port_info 4 /INPUT 6 "addr";
    .port_info 5 /INPUT 1 "rd";
    .port_info 6 /INPUT 1 "wr";
    .port_info 7 /OUTPUT 16 "d_out";
v0x2151d7e0_0 .net "CENT", 3 0, L_0x215203b0;  1 drivers
v0x2151d8c0_0 .net "CLK", 0 0, v0x2151ec70_0;  1 drivers
v0x2151d980_0 .net "DEC", 3 0, L_0x215202c0;  1 drivers
v0x2151da20_0 .net "DONE", 0 0, v0x215193d0_0;  1 drivers
v0x2151dac0_0 .var "INIT", 0 0;
v0x2151dbb0_0 .net "MIL", 3 0, L_0x21520450;  1 drivers
v0x2151dc50_0 .var "Op_A", 15 0;
v0x2151dd60_0 .net "RESULT", 15 0, L_0x2151f760;  1 drivers
v0x2151de40_0 .net "UNIT", 3 0, L_0x21520220;  1 drivers
v0x2151df90_0 .net "addr", 5 0, v0x2151f240_0;  1 drivers
v0x2151e070_0 .net "cs", 0 0, v0x2151f300_0;  1 drivers
v0x2151e130_0 .net "d_in", 15 0, v0x2151f3a0_0;  1 drivers
v0x2151e210_0 .var "d_out", 15 0;
v0x2151e2f0_0 .net "rd", 0 0, v0x2151f580_0;  1 drivers
v0x2151e3b0_0 .net "reset", 0 0, v0x2151f620_0;  1 drivers
v0x2151e470_0 .var "s", 3 0;
v0x2151e550_0 .net "wr", 0 0, v0x2151f6c0_0;  1 drivers
E_0x214b3e80 .event anyedge, v0x2151e070_0, v0x2151df90_0;
L_0x2151f760 .concat [ 4 4 4 4], L_0x21520220, L_0x215202c0, L_0x215203b0, L_0x21520450;
S_0x21518630 .scope module, "u_BinarioABCD" "BinarioABCD" 3 73, 4 1 0, S_0x215183c0;
 .timescale 0 0;
    .port_info 0 /INPUT 1 "CLK";
    .port_info 1 /INPUT 16 "Op_A";
    .port_info 2 /INPUT 1 "INIT";
    .port_info 3 /OUTPUT 4 "UNIT";
    .port_info 4 /OUTPUT 4 "DEC";
    .port_info 5 /OUTPUT 4 "CENT";
    .port_info 6 /OUTPUT 4 "MIL";
    .port_info 7 /OUTPUT 1 "DONE";
v0x2151c5c0_0 .net "CENT", 3 0, L_0x215203b0;  alias, 1 drivers
v0x2151c6a0_0 .net "CLK", 0 0, v0x2151ec70_0;  alias, 1 drivers
v0x2151c760_0 .net "DEC", 3 0, L_0x215202c0;  alias, 1 drivers
v0x2151c850_0 .net "DONE", 0 0, v0x215193d0_0;  alias, 1 drivers
v0x2151c8f0_0 .net "INIT", 0 0, v0x2151dac0_0;  1 drivers
v0x2151c9e0_0 .net "MIL", 3 0, L_0x21520450;  alias, 1 drivers
v0x2151cad0_0 .net "Op_A", 15 0, v0x2151dc50_0;  1 drivers
v0x2151cb70_0 .net "UNIT", 3 0, L_0x21520220;  alias, 1 drivers
v0x2151cc60_0 .net "W_ADD3", 0 0, v0x214ac070_0;  1 drivers
v0x2151cd00_0 .net "W_CENTN", 3 0, v0x2151b090_0;  1 drivers
v0x2151cdf0_0 .net "W_DEC", 0 0, v0x21519330_0;  1 drivers
v0x2151cee0_0 .net "W_DECN", 3 0, v0x2151b260_0;  1 drivers
v0x2151cff0_0 .net "W_LD", 0 0, v0x21519560_0;  1 drivers
v0x2151d090_0 .net "W_MILN", 3 0, v0x2151b420_0;  1 drivers
v0x2151d1a0_0 .net "W_MSB", 0 0, L_0x214ee5a0;  1 drivers
v0x2151d290_0 .net "W_SH", 0 0, v0x21519740_0;  1 drivers
v0x2151d380_0 .net "W_UNITN", 3 0, v0x2151b720_0;  1 drivers
v0x2151d5a0_0 .net "W_Z", 0 0, v0x214f0c60_0;  1 drivers
S_0x21518880 .scope module, "CONTADOR_BBCD0" "CONTADOR_BBCD" 4 41, 5 1 0, S_0x21518630;
 .timescale 0 0;
    .port_info 0 /INPUT 1 "CLK";
    .port_info 1 /INPUT 1 "LD";
    .port_info 2 /INPUT 1 "DEC";
    .port_info 3 /OUTPUT 1 "Z";
v0x214f6630_0 .net "CLK", 0 0, v0x2151ec70_0;  alias, 1 drivers
v0x214f72d0_0 .net "DEC", 0 0, v0x21519330_0;  alias, 1 drivers
v0x214f0710_0 .net "LD", 0 0, v0x21519560_0;  alias, 1 drivers
v0x214f0c60_0 .var "Z", 0 0;
v0x214ee390_0 .var "count", 4 0;
S_0x21518c10 .scope module, "CONTROL_BBCD0" "CONTROL_BBCD" 4 66, 6 1 0, S_0x21518630;
 .timescale 0 0;
    .port_info 0 /INPUT 1 "CLK";
    .port_info 1 /INPUT 1 "MSB";
    .port_info 2 /INPUT 1 "Z";
    .port_info 3 /INPUT 1 "INIT";
    .port_info 4 /OUTPUT 1 "LD";
    .port_info 5 /OUTPUT 1 "DEC";
    .port_info 6 /OUTPUT 1 "SH";
    .port_info 7 /OUTPUT 1 "ADD3";
    .port_info 8 /OUTPUT 1 "DONE";
P_0x21518e10 .param/l "S_CHECK" 0 6 18, C4<011>;
P_0x21518e50 .param/l "S_END1" 0 6 19, C4<100>;
P_0x21518e90 .param/l "S_SHIFT_DEC" 0 6 17, C4<010>;
P_0x21518ed0 .param/l "S_START" 0 6 15, C4<000>;
P_0x21518f10 .param/l "S_SUM" 0 6 16, C4<001>;
v0x214ac070_0 .var "ADD3", 0 0;
v0x21519270_0 .net "CLK", 0 0, v0x2151ec70_0;  alias, 1 drivers
v0x21519330_0 .var "DEC", 0 0;
v0x215193d0_0 .var "DONE", 0 0;
v0x21519470_0 .net "INIT", 0 0, v0x2151dac0_0;  alias, 1 drivers
v0x21519560_0 .var "LD", 0 0;
v0x21519600_0 .net "MSB", 0 0, L_0x214ee5a0;  alias, 1 drivers
v0x215196a0_0 .var "NEXT_STATE", 2 0;
v0x21519740_0 .var "SH", 0 0;
v0x21519800_0 .var "STATE", 2 0;
v0x215198e0_0 .net "Z", 0 0, v0x214f0c60_0;  alias, 1 drivers
E_0x214b43c0 .event anyedge, v0x21519800_0;
E_0x214b3910 .event anyedge, v0x21519800_0, v0x21519470_0, v0x214f0c60_0, v0x21519600_0;
S_0x21519a80 .scope module, "LSR_BBCD0" "LSR_BBCD" 4 48, 7 1 0, S_0x21518630;
 .timescale 0 0;
    .port_info 0 /INPUT 1 "CLK";
    .port_info 1 /INPUT 1 "SH";
    .port_info 2 /INPUT 1 "LD";
    .port_info 3 /INPUT 16 "Op_A_in";
    .port_info 4 /INPUT 4 "UNITN";
    .port_info 5 /INPUT 4 "DECN";
    .port_info 6 /INPUT 4 "CENTN";
    .port_info 7 /INPUT 4 "MILN";
    .port_info 8 /OUTPUT 4 "UNIT";
    .port_info 9 /OUTPUT 4 "DEC";
    .port_info 10 /OUTPUT 4 "CENT";
    .port_info 11 /OUTPUT 4 "MIL";
v0x21519da0_0 .var "A", 15 0;
v0x21519e80_0 .net "CENT", 3 0, L_0x215203b0;  alias, 1 drivers
v0x21519f60_0 .net "CENTN", 3 0, v0x2151b090_0;  alias, 1 drivers
v0x2151a020_0 .net "CLK", 0 0, v0x2151ec70_0;  alias, 1 drivers
v0x2151a110_0 .net "DEC", 3 0, L_0x215202c0;  alias, 1 drivers
v0x2151a240_0 .net "DECN", 3 0, v0x2151b260_0;  alias, 1 drivers
v0x2151a320_0 .net "LD", 0 0, v0x21519560_0;  alias, 1 drivers
v0x2151a410_0 .net "MIL", 3 0, L_0x21520450;  alias, 1 drivers
v0x2151a4f0_0 .net "MILN", 3 0, v0x2151b420_0;  alias, 1 drivers
v0x2151a660_0 .var "Op_A", 15 0;
v0x2151a740_0 .net "Op_A_in", 15 0, v0x2151dc50_0;  alias, 1 drivers
v0x2151a820_0 .net "SH", 0 0, v0x21519740_0;  alias, 1 drivers
v0x2151a8c0_0 .net "UNIT", 3 0, L_0x21520220;  alias, 1 drivers
v0x2151a980_0 .net "UNITN", 3 0, v0x2151b720_0;  alias, 1 drivers
L_0x21520220 .part v0x21519da0_0, 0, 4;
L_0x215202c0 .part v0x21519da0_0, 4, 4;
L_0x215203b0 .part v0x21519da0_0, 8, 4;
L_0x21520450 .part v0x21519da0_0, 12, 4;
S_0x2151abe0 .scope module, "SUM_C2_BBCD0" "SUM_C2_BBCD" 4 27, 8 1 0, S_0x21518630;
 .timescale 0 0;
    .port_info 0 /INPUT 1 "ADD3";
    .port_info 1 /INPUT 4 "UNIT";
    .port_info 2 /INPUT 4 "DEC";
    .port_info 3 /INPUT 4 "CENT";
    .port_info 4 /INPUT 4 "MIL";
    .port_info 5 /OUTPUT 4 "UNITN";
    .port_info 6 /OUTPUT 4 "DECN";
    .port_info 7 /OUTPUT 4 "CENTN";
    .port_info 8 /OUTPUT 4 "MILN";
    .port_info 9 /OUTPUT 1 "MSB";
L_0x214f6520 .functor OR 1, L_0x2151fae0, L_0x2151fc50, C4<0>, C4<0>;
L_0x214f0600 .functor OR 1, L_0x214f6520, L_0x2151fdf0, C4<0>, C4<0>;
L_0x214ee5a0 .functor OR 1, L_0x214f0600, L_0x21520040, C4<0>, C4<0>;
v0x2151af30_0 .net "ADD3", 0 0, v0x214ac070_0;  alias, 1 drivers
v0x2151aff0_0 .net "CENT", 3 0, L_0x215203b0;  alias, 1 drivers
v0x2151b090_0 .var "CENTN", 3 0;
v0x2151b190_0 .net "DEC", 3 0, L_0x215202c0;  alias, 1 drivers
v0x2151b260_0 .var "DECN", 3 0;
v0x2151b350_0 .net "MIL", 3 0, L_0x21520450;  alias, 1 drivers
v0x2151b420_0 .var "MILN", 3 0;
v0x2151b4f0_0 .net "MSB", 0 0, L_0x214ee5a0;  alias, 1 drivers
v0x2151b5c0_0 .net "UNIT", 3 0, L_0x21520220;  alias, 1 drivers
v0x2151b720_0 .var "UNITN", 3 0;
v0x2151b7f0_0 .net *"_ivl_1", 0 0, L_0x2151fa40;  1 drivers
v0x2151b890_0 .net *"_ivl_11", 0 0, L_0x2151fd50;  1 drivers
v0x2151b950_0 .net *"_ivl_13", 0 0, L_0x2151fdf0;  1 drivers
v0x2151ba10_0 .net *"_ivl_15", 0 0, L_0x214f0600;  1 drivers
v0x2151bad0_0 .net *"_ivl_17", 0 0, L_0x2151ffa0;  1 drivers
v0x2151bbb0_0 .net *"_ivl_19", 0 0, L_0x21520040;  1 drivers
v0x2151bc70_0 .net *"_ivl_3", 0 0, L_0x2151fae0;  1 drivers
v0x2151be40_0 .net *"_ivl_5", 0 0, L_0x2151fb80;  1 drivers
v0x2151bf20_0 .net *"_ivl_7", 0 0, L_0x2151fc50;  1 drivers
v0x2151bfe0_0 .net *"_ivl_9", 0 0, L_0x214f6520;  1 drivers
v0x2151c0a0_0 .var "diffC", 4 0;
v0x2151c180_0 .var "diffD", 4 0;
v0x2151c260_0 .var "diffM", 4 0;
v0x2151c340_0 .var "diffU", 4 0;
E_0x2149ced0/0 .event anyedge, v0x2151a8c0_0, v0x2151a110_0, v0x21519e80_0, v0x2151a410_0;
E_0x2149ced0/1 .event anyedge, v0x214ac070_0, v0x2151c340_0, v0x2151c180_0, v0x2151c0a0_0;
E_0x2149ced0/2 .event anyedge, v0x2151c260_0;
E_0x2149ced0 .event/or E_0x2149ced0/0, E_0x2149ced0/1, E_0x2149ced0/2;
L_0x2151fa40 .part v0x2151c340_0, 4, 1;
L_0x2151fae0 .reduce/nor L_0x2151fa40;
L_0x2151fb80 .part v0x2151c180_0, 4, 1;
L_0x2151fc50 .reduce/nor L_0x2151fb80;
L_0x2151fd50 .part v0x2151c0a0_0, 4, 1;
L_0x2151fdf0 .reduce/nor L_0x2151fd50;
L_0x2151ffa0 .part v0x2151c260_0, 4, 1;
L_0x21520040 .reduce/nor L_0x2151ffa0;
S_0x2151e820 .scope task, "write_reg" "write_reg" 2 57, 2 57 0, S_0x214f8670;
 .timescale -9 -12;
v0x2151e9b0_0 .var "address", 5 0;
v0x2151ea90_0 .var "data", 15 0;
TD_tb_Periferico_BinarioABCD.write_reg ;
    %wait E_0x214b3720;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x2151f300_0, 0, 1;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x2151f6c0_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2151f580_0, 0, 1;
    %load/vec4 v0x2151e9b0_0;
    %store/vec4 v0x2151f240_0, 0, 6;
    %load/vec4 v0x2151ea90_0;
    %store/vec4 v0x2151f3a0_0, 0, 16;
    %wait E_0x214b3720;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2151f300_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2151f6c0_0, 0, 1;
    %pushi/vec4 0, 0, 16;
    %store/vec4 v0x2151f3a0_0, 0, 16;
    %vpi_call 2 69 "$display", "[%0t] WRITE addr=0x%0h data=%0d (0x%0h)", $time, v0x2151e9b0_0, v0x2151ea90_0, v0x2151ea90_0 {0 0 0};
    %end;
    .scope S_0x2151abe0;
T_2 ;
    %wait E_0x2149ced0;
    %pushi/vec4 0, 0, 1;
    %load/vec4 v0x2151b5c0_0;
    %concat/vec4; draw_concat_vec4
    %addi 27, 0, 5;
    %store/vec4 v0x2151c340_0, 0, 5;
    %pushi/vec4 0, 0, 1;
    %load/vec4 v0x2151b190_0;
    %concat/vec4; draw_concat_vec4
    %addi 27, 0, 5;
    %store/vec4 v0x2151c180_0, 0, 5;
    %pushi/vec4 0, 0, 1;
    %load/vec4 v0x2151aff0_0;
    %concat/vec4; draw_concat_vec4
    %addi 27, 0, 5;
    %store/vec4 v0x2151c0a0_0, 0, 5;
    %pushi/vec4 0, 0, 1;
    %load/vec4 v0x2151b350_0;
    %concat/vec4; draw_concat_vec4
    %addi 27, 0, 5;
    %store/vec4 v0x2151c260_0, 0, 5;
    %load/vec4 v0x2151b5c0_0;
    %store/vec4 v0x2151b720_0, 0, 4;
    %load/vec4 v0x2151b190_0;
    %store/vec4 v0x2151b260_0, 0, 4;
    %load/vec4 v0x2151aff0_0;
    %store/vec4 v0x2151b090_0, 0, 4;
    %load/vec4 v0x2151b350_0;
    %store/vec4 v0x2151b420_0, 0, 4;
    %load/vec4 v0x2151af30_0;
    %flag_set/vec4 9;
    %flag_get/vec4 9;
    %jmp/0 T_2.2, 9;
    %load/vec4 v0x2151c340_0;
    %parti/s 1, 4, 4;
    %pushi/vec4 0, 0, 1;
    %cmp/e;
    %flag_get/vec4 4;
    %and;
T_2.2;
    %flag_set/vec4 8;
    %jmp/0xz  T_2.0, 8;
    %load/vec4 v0x2151b5c0_0;
    %addi 3, 0, 4;
    %store/vec4 v0x2151b720_0, 0, 4;
T_2.0 ;
    %load/vec4 v0x2151af30_0;
    %flag_set/vec4 9;
    %flag_get/vec4 9;
    %jmp/0 T_2.5, 9;
    %load/vec4 v0x2151c180_0;
    %parti/s 1, 4, 4;
    %pushi/vec4 0, 0, 1;
    %cmp/e;
    %flag_get/vec4 4;
    %and;
T_2.5;
    %flag_set/vec4 8;
    %jmp/0xz  T_2.3, 8;
    %load/vec4 v0x2151b190_0;
    %addi 3, 0, 4;
    %store/vec4 v0x2151b260_0, 0, 4;
T_2.3 ;
    %load/vec4 v0x2151af30_0;
    %flag_set/vec4 9;
    %flag_get/vec4 9;
    %jmp/0 T_2.8, 9;
    %load/vec4 v0x2151c0a0_0;
    %parti/s 1, 4, 4;
    %pushi/vec4 0, 0, 1;
    %cmp/e;
    %flag_get/vec4 4;
    %and;
T_2.8;
    %flag_set/vec4 8;
    %jmp/0xz  T_2.6, 8;
    %load/vec4 v0x2151aff0_0;
    %addi 3, 0, 4;
    %store/vec4 v0x2151b090_0, 0, 4;
T_2.6 ;
    %load/vec4 v0x2151af30_0;
    %flag_set/vec4 9;
    %flag_get/vec4 9;
    %jmp/0 T_2.11, 9;
    %load/vec4 v0x2151c260_0;
    %parti/s 1, 4, 4;
    %pushi/vec4 0, 0, 1;
    %cmp/e;
    %flag_get/vec4 4;
    %and;
T_2.11;
    %flag_set/vec4 8;
    %jmp/0xz  T_2.9, 8;
    %load/vec4 v0x2151b350_0;
    %addi 3, 0, 4;
    %store/vec4 v0x2151b420_0, 0, 4;
T_2.9 ;
    %jmp T_2;
    .thread T_2, $push;
    .scope S_0x21518880;
T_3 ;
    %wait E_0x214b3720;
    %load/vec4 v0x214f0710_0;
    %flag_set/vec4 8;
    %jmp/0xz  T_3.0, 8;
    %pushi/vec4 15, 0, 5;
    %assign/vec4 v0x214ee390_0, 0;
    %pushi/vec4 0, 0, 1;
    %assign/vec4 v0x214f0c60_0, 0;
    %jmp T_3.1;
T_3.0 ;
    %load/vec4 v0x214f72d0_0;
    %flag_set/vec4 9;
    %flag_get/vec4 9;
    %jmp/0 T_3.4, 9;
    %load/vec4 v0x214ee390_0;
    %pad/u 32;
    %pushi/vec4 0, 0, 32;
    %cmp/ne;
    %flag_get/vec4 4;
    %and;
T_3.4;
    %flag_set/vec4 8;
    %jmp/0xz  T_3.2, 8;
    %load/vec4 v0x214ee390_0;
    %subi 1, 0, 5;
    %assign/vec4 v0x214ee390_0, 0;
    %jmp T_3.3;
T_3.2 ;
    %load/vec4 v0x214ee390_0;
    %pad/u 32;
    %cmpi/e 0, 0, 32;
    %jmp/0xz  T_3.5, 4;
    %pushi/vec4 1, 0, 1;
    %assign/vec4 v0x214f0c60_0, 0;
T_3.5 ;
T_3.3 ;
T_3.1 ;
    %jmp T_3;
    .thread T_3;
    .scope S_0x21519a80;
T_4 ;
    %wait E_0x214b3720;
    %load/vec4 v0x2151a320_0;
    %flag_set/vec4 8;
    %jmp/0xz  T_4.0, 8;
    %pushi/vec4 0, 0, 16;
    %assign/vec4 v0x21519da0_0, 0;
    %load/vec4 v0x2151a740_0;
    %assign/vec4 v0x2151a660_0, 0;
    %jmp T_4.1;
T_4.0 ;
    %load/vec4 v0x2151a820_0;
    %flag_set/vec4 8;
    %jmp/0xz  T_4.2, 8;
    %load/vec4 v0x21519da0_0;
    %load/vec4 v0x2151a660_0;
    %concat/vec4; draw_concat_vec4
    %ix/load 4, 1, 0;
    %flag_set/imm 4, 0;
    %shiftl 4;
    %split/vec4 16;
    %assign/vec4 v0x2151a660_0, 0;
    %assign/vec4 v0x21519da0_0, 0;
    %jmp T_4.3;
T_4.2 ;
    %load/vec4 v0x2151a980_0;
    %ix/load 4, 0, 0;
    %ix/load 5, 0, 0;
    %flag_set/imm 4, 0;
    %assign/vec4/off/d v0x21519da0_0, 4, 5;
    %load/vec4 v0x2151a240_0;
    %ix/load 4, 4, 0;
    %ix/load 5, 0, 0;
    %flag_set/imm 4, 0;
    %assign/vec4/off/d v0x21519da0_0, 4, 5;
    %load/vec4 v0x21519f60_0;
    %ix/load 4, 8, 0;
    %ix/load 5, 0, 0;
    %flag_set/imm 4, 0;
    %assign/vec4/off/d v0x21519da0_0, 4, 5;
    %load/vec4 v0x2151a4f0_0;
    %ix/load 4, 12, 0;
    %ix/load 5, 0, 0;
    %flag_set/imm 4, 0;
    %assign/vec4/off/d v0x21519da0_0, 4, 5;
T_4.3 ;
T_4.1 ;
    %jmp T_4;
    .thread T_4;
    .scope S_0x21518c10;
T_5 ;
    %wait E_0x214b3720;
    %load/vec4 v0x215196a0_0;
    %assign/vec4 v0x21519800_0, 0;
    %jmp T_5;
    .thread T_5;
    .scope S_0x21518c10;
T_6 ;
    %wait E_0x214b3910;
    %load/vec4 v0x21519800_0;
    %dup/vec4;
    %pushi/vec4 0, 0, 3;
    %cmp/u;
    %jmp/1 T_6.0, 6;
    %dup/vec4;
    %pushi/vec4 1, 0, 3;
    %cmp/u;
    %jmp/1 T_6.1, 6;
    %dup/vec4;
    %pushi/vec4 2, 0, 3;
    %cmp/u;
    %jmp/1 T_6.2, 6;
    %dup/vec4;
    %pushi/vec4 3, 0, 3;
    %cmp/u;
    %jmp/1 T_6.3, 6;
    %dup/vec4;
    %pushi/vec4 4, 0, 3;
    %cmp/u;
    %jmp/1 T_6.4, 6;
    %pushi/vec4 0, 0, 3;
    %store/vec4 v0x215196a0_0, 0, 3;
    %jmp T_6.6;
T_6.0 ;
    %load/vec4 v0x21519470_0;
    %flag_set/vec4 8;
    %jmp/0xz  T_6.7, 8;
    %pushi/vec4 1, 0, 3;
    %store/vec4 v0x215196a0_0, 0, 3;
    %jmp T_6.8;
T_6.7 ;
    %pushi/vec4 0, 0, 3;
    %store/vec4 v0x215196a0_0, 0, 3;
T_6.8 ;
    %jmp T_6.6;
T_6.1 ;
    %pushi/vec4 2, 0, 3;
    %store/vec4 v0x215196a0_0, 0, 3;
    %jmp T_6.6;
T_6.2 ;
    %pushi/vec4 3, 0, 3;
    %store/vec4 v0x215196a0_0, 0, 3;
    %jmp T_6.6;
T_6.3 ;
    %load/vec4 v0x215198e0_0;
    %flag_set/vec4 8;
    %jmp/0xz  T_6.9, 8;
    %pushi/vec4 4, 0, 3;
    %store/vec4 v0x215196a0_0, 0, 3;
    %jmp T_6.10;
T_6.9 ;
    %load/vec4 v0x21519600_0;
    %nor/r;
    %flag_set/vec4 9;
    %flag_get/vec4 9;
    %jmp/0 T_6.13, 9;
    %load/vec4 v0x215198e0_0;
    %nor/r;
    %and;
T_6.13;
    %flag_set/vec4 8;
    %jmp/0xz  T_6.11, 8;
    %pushi/vec4 2, 0, 3;
    %store/vec4 v0x215196a0_0, 0, 3;
    %jmp T_6.12;
T_6.11 ;
    %load/vec4 v0x21519600_0;
    %flag_set/vec4 9;
    %flag_get/vec4 9;
    %jmp/0 T_6.16, 9;
    %load/vec4 v0x215198e0_0;
    %nor/r;
    %and;
T_6.16;
    %flag_set/vec4 8;
    %jmp/0xz  T_6.14, 8;
    %pushi/vec4 1, 0, 3;
    %store/vec4 v0x215196a0_0, 0, 3;
    %jmp T_6.15;
T_6.14 ;
    %pushi/vec4 3, 0, 3;
    %store/vec4 v0x215196a0_0, 0, 3;
T_6.15 ;
T_6.12 ;
T_6.10 ;
    %jmp T_6.6;
T_6.4 ;
    %pushi/vec4 4, 0, 3;
    %store/vec4 v0x215196a0_0, 0, 3;
    %jmp T_6.6;
T_6.6 ;
    %pop/vec4 1;
    %jmp T_6;
    .thread T_6, $push;
    .scope S_0x21518c10;
T_7 ;
    %wait E_0x214b43c0;
    %load/vec4 v0x21519800_0;
    %dup/vec4;
    %pushi/vec4 0, 0, 3;
    %cmp/u;
    %jmp/1 T_7.0, 6;
    %dup/vec4;
    %pushi/vec4 1, 0, 3;
    %cmp/u;
    %jmp/1 T_7.1, 6;
    %dup/vec4;
    %pushi/vec4 2, 0, 3;
    %cmp/u;
    %jmp/1 T_7.2, 6;
    %dup/vec4;
    %pushi/vec4 3, 0, 3;
    %cmp/u;
    %jmp/1 T_7.3, 6;
    %dup/vec4;
    %pushi/vec4 4, 0, 3;
    %cmp/u;
    %jmp/1 T_7.4, 6;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x215193d0_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x21519740_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x21519560_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x21519330_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x214ac070_0, 0, 1;
    %jmp T_7.6;
T_7.0 ;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x215193d0_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x21519740_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x21519330_0, 0, 1;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x21519560_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x214ac070_0, 0, 1;
    %jmp T_7.6;
T_7.1 ;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x215193d0_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x21519740_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x21519330_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x21519560_0, 0, 1;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x214ac070_0, 0, 1;
    %jmp T_7.6;
T_7.2 ;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x215193d0_0, 0, 1;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x21519740_0, 0, 1;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x21519330_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x21519560_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x214ac070_0, 0, 1;
    %jmp T_7.6;
T_7.3 ;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x215193d0_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x21519740_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x21519330_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x21519560_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x214ac070_0, 0, 1;
    %jmp T_7.6;
T_7.4 ;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x215193d0_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x21519740_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x21519330_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x21519560_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x214ac070_0, 0, 1;
    %jmp T_7.6;
T_7.6 ;
    %pop/vec4 1;
    %jmp T_7;
    .thread T_7, $push;
    .scope S_0x215183c0;
T_8 ;
    %wait E_0x214b3e80;
    %load/vec4 v0x2151e070_0;
    %flag_set/vec4 8;
    %jmp/0xz  T_8.0, 8;
    %load/vec4 v0x2151df90_0;
    %dup/vec4;
    %pushi/vec4 4, 0, 6;
    %cmp/u;
    %jmp/1 T_8.2, 6;
    %dup/vec4;
    %pushi/vec4 8, 0, 6;
    %cmp/u;
    %jmp/1 T_8.3, 6;
    %dup/vec4;
    %pushi/vec4 12, 0, 6;
    %cmp/u;
    %jmp/1 T_8.4, 6;
    %dup/vec4;
    %pushi/vec4 16, 0, 6;
    %cmp/u;
    %jmp/1 T_8.5, 6;
    %pushi/vec4 0, 0, 4;
    %store/vec4 v0x2151e470_0, 0, 4;
    %jmp T_8.7;
T_8.2 ;
    %pushi/vec4 1, 0, 4;
    %store/vec4 v0x2151e470_0, 0, 4;
    %jmp T_8.7;
T_8.3 ;
    %pushi/vec4 2, 0, 4;
    %store/vec4 v0x2151e470_0, 0, 4;
    %jmp T_8.7;
T_8.4 ;
    %pushi/vec4 4, 0, 4;
    %store/vec4 v0x2151e470_0, 0, 4;
    %jmp T_8.7;
T_8.5 ;
    %pushi/vec4 8, 0, 4;
    %store/vec4 v0x2151e470_0, 0, 4;
    %jmp T_8.7;
T_8.7 ;
    %pop/vec4 1;
    %jmp T_8.1;
T_8.0 ;
    %pushi/vec4 0, 0, 4;
    %store/vec4 v0x2151e470_0, 0, 4;
T_8.1 ;
    %jmp T_8;
    .thread T_8, $push;
    .scope S_0x215183c0;
T_9 ;
    %wait E_0x214b3720;
    %load/vec4 v0x2151e3b0_0;
    %flag_set/vec4 8;
    %jmp/0xz  T_9.0, 8;
    %pushi/vec4 0, 0, 16;
    %assign/vec4 v0x2151dc50_0, 0;
    %pushi/vec4 0, 0, 1;
    %assign/vec4 v0x2151dac0_0, 0;
    %jmp T_9.1;
T_9.0 ;
    %load/vec4 v0x2151e070_0;
    %flag_set/vec4 9;
    %flag_get/vec4 9;
    %jmp/0 T_9.4, 9;
    %load/vec4 v0x2151e550_0;
    %and;
T_9.4;
    %flag_set/vec4 8;
    %jmp/0xz  T_9.2, 8;
    %load/vec4 v0x2151e470_0;
    %parti/s 1, 0, 2;
    %flag_set/vec4 8;
    %jmp/0 T_9.5, 8;
    %load/vec4 v0x2151e130_0;
    %jmp/1 T_9.6, 8;
T_9.5 ; End of true expr.
    %load/vec4 v0x2151dc50_0;
    %jmp/0 T_9.6, 8;
 ; End of false expr.
    %blend;
T_9.6;
    %assign/vec4 v0x2151dc50_0, 0;
    %load/vec4 v0x2151e470_0;
    %parti/s 1, 1, 2;
    %flag_set/vec4 8;
    %jmp/0 T_9.7, 8;
    %load/vec4 v0x2151e130_0;
    %parti/s 1, 0, 2;
    %jmp/1 T_9.8, 8;
T_9.7 ; End of true expr.
    %load/vec4 v0x2151dac0_0;
    %jmp/0 T_9.8, 8;
 ; End of false expr.
    %blend;
T_9.8;
    %assign/vec4 v0x2151dac0_0, 0;
T_9.2 ;
T_9.1 ;
    %jmp T_9;
    .thread T_9;
    .scope S_0x215183c0;
T_10 ;
    %wait E_0x214b3720;
    %load/vec4 v0x2151e3b0_0;
    %flag_set/vec4 8;
    %jmp/0xz  T_10.0, 8;
    %pushi/vec4 0, 0, 16;
    %assign/vec4 v0x2151e210_0, 0;
    %jmp T_10.1;
T_10.0 ;
    %load/vec4 v0x2151e070_0;
    %flag_set/vec4 9;
    %flag_get/vec4 9;
    %jmp/0 T_10.4, 9;
    %load/vec4 v0x2151e2f0_0;
    %and;
T_10.4;
    %flag_set/vec4 8;
    %jmp/0xz  T_10.2, 8;
    %load/vec4 v0x2151e470_0;
    %dup/vec4;
    %pushi/vec4 4, 0, 4;
    %cmp/u;
    %jmp/1 T_10.5, 6;
    %dup/vec4;
    %pushi/vec4 8, 0, 4;
    %cmp/u;
    %jmp/1 T_10.6, 6;
    %pushi/vec4 0, 0, 16;
    %assign/vec4 v0x2151e210_0, 0;
    %jmp T_10.8;
T_10.5 ;
    %load/vec4 v0x2151dd60_0;
    %assign/vec4 v0x2151e210_0, 0;
    %jmp T_10.8;
T_10.6 ;
    %pushi/vec4 0, 0, 15;
    %load/vec4 v0x2151da20_0;
    %concat/vec4; draw_concat_vec4
    %assign/vec4 v0x2151e210_0, 0;
    %jmp T_10.8;
T_10.8 ;
    %pop/vec4 1;
T_10.2 ;
T_10.1 ;
    %jmp T_10;
    .thread T_10;
    .scope S_0x214f8670;
T_11 ;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2151ec70_0, 0, 1;
T_11.0 ;
    %delay 5000, 0;
    %load/vec4 v0x2151ec70_0;
    %inv;
    %store/vec4 v0x2151ec70_0, 0, 1;
    %jmp T_11.0;
T_11.1 ;
    %end;
    .thread T_11;
    .scope S_0x214f8670;
T_12 ;
    %vpi_call 2 88 "$dumpfile", "tb_Periferico_BinarioABCD.vcd" {0 0 0};
    %vpi_call 2 89 "$dumpvars", 32'sb00000000000000000000000000000000, S_0x214f8670 {0 0 0};
    %end;
    .thread T_12;
    .scope S_0x214f8670;
T_13 ;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x2151f620_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2151f300_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2151f6c0_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2151f580_0, 0, 1;
    %pushi/vec4 0, 0, 6;
    %store/vec4 v0x2151f240_0, 0, 6;
    %pushi/vec4 0, 0, 16;
    %store/vec4 v0x2151f3a0_0, 0, 16;
    %delay 20000, 0;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2151f620_0, 0, 1;
    %vpi_call 2 104 "$display", "\012 Prueba de conversi\303\263n BIN->BCD\012" {0 0 0};
    %pushi/vec4 4, 0, 6;
    %store/vec4 v0x2151e9b0_0, 0, 6;
    %pushi/vec4 1234, 0, 16;
    %store/vec4 v0x2151ea90_0, 0, 16;
    %fork TD_tb_Periferico_BinarioABCD.write_reg, S_0x2151e820;
    %join;
    %pushi/vec4 8, 0, 6;
    %store/vec4 v0x2151e9b0_0, 0, 6;
    %pushi/vec4 1, 0, 16;
    %store/vec4 v0x2151ea90_0, 0, 16;
    %fork TD_tb_Periferico_BinarioABCD.write_reg, S_0x2151e820;
    %join;
    %pushi/vec4 0, 0, 32;
    %store/vec4 v0x2151f4e0_0, 0, 32;
T_13.0 ; Top of for-loop 
    %load/vec4 v0x2151f4e0_0;
    %cmpi/s 500, 0, 32;
    %jmp/0xz T_13.1, 5;
    %wait E_0x214b3720;
    %load/vec4 v0x2151edd0_0;
    %flag_set/vec4 8;
    %jmp/0xz  T_13.3, 8;
    %vpi_call 2 114 "$display", "\012 DONE detectado en t=%0t", $time {0 0 0};
    %pushi/vec4 500, 0, 32;
    %store/vec4 v0x2151f4e0_0, 0, 32;
T_13.3 ;
T_13.2 ; for-loop step statement
    %load/vec4 v0x2151f4e0_0;
    %addi 1, 0, 32;
    %store/vec4 v0x2151f4e0_0, 0, 32;
    %jmp T_13.0;
T_13.1 ; for-loop exit label
    %pushi/vec4 12, 0, 6;
    %store/vec4 v0x214ad210_0, 0, 6;
    %fork TD_tb_Periferico_BinarioABCD.read_reg, S_0x214b77e0;
    %join;
    %pushi/vec4 16, 0, 6;
    %store/vec4 v0x214ad210_0, 0, 6;
    %fork TD_tb_Periferico_BinarioABCD.read_reg, S_0x214b77e0;
    %join;
    %pushi/vec4 20, 0, 6;
    %store/vec4 v0x214ad210_0, 0, 6;
    %fork TD_tb_Periferico_BinarioABCD.read_reg, S_0x214b77e0;
    %join;
    %pushi/vec4 24, 0, 6;
    %store/vec4 v0x214ad210_0, 0, 6;
    %fork TD_tb_Periferico_BinarioABCD.read_reg, S_0x214b77e0;
    %join;
    %pushi/vec4 28, 0, 6;
    %store/vec4 v0x214ad210_0, 0, 6;
    %fork TD_tb_Periferico_BinarioABCD.read_reg, S_0x214b77e0;
    %join;
    %vpi_call 2 126 "$display", "\012[RESULTADO FINAL]" {0 0 0};
    %vpi_call 2 127 "$display", "BIN = %0d (0x%0h)", v0x2151f080_0, v0x2151f080_0 {0 0 0};
    %vpi_call 2 128 "$display", "BCD = %1d%1d%1d%1d", v0x2151efa0_0, v0x2151eb70_0, v0x2151ed30_0, v0x2151f160_0 {0 0 0};
    %delay 50000, 0;
    %vpi_call 2 131 "$display", "\012=== FIN DE SIMULACI\303\223N ===" {0 0 0};
    %vpi_call 2 132 "$finish" {0 0 0};
    %end;
    .thread T_13;
# The file index is used to find the file name in the following table.
:file_names 9;
    "N/A";
    "<interactive>";
    "testbench.v";
    "Periferico_BBCD.v";
    "Binario-BCD.v";
    "CONTADOR_BBCD.v";
    "CONTROL_BBCD.v";
    "LSR_BBCD.v";
    "SUM_C2_BBCD.v";
# EOF
